# Debug options are in zmw.h

# Profiling or Optimizing?
ZMW_GPROF_PROFILING=
ZMW_GPROF_PROFILING=-pg
ZMW_GPROF_PROFILING=-Os
ZMW_GPROF_PROFILING=-O6

# Version number
ZMW_VERSION_MAJOR=0
ZMW_VERSION_MINOR=2
ZMW_VERSION_MICRO=1
ZMW_VERSION=$(ZMW_VERSION_MAJOR).$(ZMW_VERSION_MINOR).$(ZMW_VERSION_MICRO)


# To use GTK1
ZMW_CFLAGS=$$(gtk-config --cflags) $$(gdk-pixbuf-config --cflags)
ZMW_LIBS=$$(gtk-config --libs) $$(gdk-pixbuf-config --libs)
# To use GTK2
ZMW_CFLAGS=$$(pkg-config gdk-2.0 --cflags) # -DGDK_DISABLE_DEPRECATED=1
ZMW_LIBS=$$(pkg-config gdk-2.0 --libs)



# No configuration option after this line


ZMW_ROOT ?= $$(ZMWP=$$(pwd) ; while [ ! -d $$ZMWP/kernel ] ; do ZMWP=$$(dirname $$ZMWP) ; done ; echo -n $$ZMWP)
ZMW_INCLUDES=$(ZMW_CFLAGS) -I$(ZMW_ROOT)/include

CFLAGS=-Wall \
       $(ZMW_GPROF_PROFILING) \
       -g \
       -DZMW_VERSION_MAJOR=$(ZMW_VERSION_MAJOR) \
       -DZMW_VERSION_MINOR=$(ZMW_VERSION_MINOR) \
       -DZMW_VERSION_MICRO=$(ZMW_VERSION_MICRO) \
       $(ZMW_INCLUDES) \
       -shared

ZMW_OBJS=$(ZMW_ROOT)/zmw.so $(ZMW_LIBS)

ZMW_FOR=for I in */Makefile ; do if [ "$$I" != "*/Makefile" -a ! -h "$$(dirname $$I)" ] ; then ( cd $$(dirname $$I) ; echo "Make $@ $$(pwd)" ; $(MAKE) $@ ) ; else true ; fi ; done

ZMW_LINK=zmwlink() { echo "Linking $@" ; $(CC) $$* $(ZMW_OBJS) -o $@ ; } ; zmwlink


.SILENT:

.c.o:
	echo "Compiling $*.c"
	$(CC) -c $(CFLAGS) $$(pwd)/$*.c -o $*.o
	touch xxx.changed

dep:
	# makedepend $(ZMW_INCLUDES) *.c 2>/dev/null
	-$(CC) -MM $(ZMW_INCLUDES) *.c >Makefile.dep
	$(ZMW_FOR)

clean::
	rm -f *.o *~ *.bak *.a gmon.out a.out TAGS tags xxx* xvfb.pid 2>/dev/null
	rm -rf .xvpics 2>/dev/null
	$(ZMW_FOR)

lib test exe doc::
	$(ZMW_FOR)

displayversion:
	echo "$(ZMW_VERSION)"

displayoptions:
	echo "PROFILING=$(ZMW_GPROF_PROFILING)"

include Makefile.dep

