O=socket.o http.o

local_all:: utilities.a

utilities.a: $(O)
	ar -r $@ $(O)

include ../Makefile

# DO NOT DELETE

http.o: /usr/include/ctype.h /usr/include/features.h /usr/include/sys/cdefs.h
http.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
http.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
http.o: /usr/include/endian.h /usr/include/bits/endian.h ../kernel/zmw.h
http.o: /usr/include/gtk-1.2/gdk/gdk.h /usr/include/gtk-1.2/gdk/gdktypes.h
http.o: /usr/include/glib-1.2/glib.h /usr/lib/glib/include/glibconfig.h
http.o: /usr/include/limits.h
http.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
http.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
http.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
http.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
http.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
http.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
http.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
http.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
http.o: /usr/include/wchar.h /usr/include/bits/wchar.h /usr/include/gconv.h
http.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
http.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
http.o: /usr/include/stdlib.h /usr/include/unistd.h
http.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
http.o: /usr/include/string.h ../widgets/zmw_widgets.h socket.h
socket.o: /usr/include/sys/socket.h /usr/include/features.h
socket.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
socket.o: /usr/include/sys/uio.h /usr/include/sys/types.h
socket.o: /usr/include/bits/types.h
socket.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
socket.o: /usr/include/time.h /usr/include/bits/uio.h
socket.o: /usr/include/bits/socket.h /usr/include/limits.h
socket.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
socket.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
socket.o: /usr/include/asm/sockios.h /usr/include/netinet/in.h
socket.o: /usr/include/stdint.h /usr/include/bits/wchar.h
socket.o: /usr/include/bits/wordsize.h /usr/include/bits/in.h
socket.o: /usr/include/endian.h /usr/include/bits/endian.h
socket.o: /usr/include/bits/byteswap.h /usr/include/sys/wait.h
socket.o: /usr/include/signal.h /usr/include/bits/sigset.h
socket.o: /usr/include/bits/signum.h /usr/include/sys/resource.h
socket.o: /usr/include/bits/resource.h /usr/include/bits/time.h
socket.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
socket.o: /usr/include/netdb.h /usr/include/bits/netdb.h /usr/include/stdio.h
socket.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
socket.o: /usr/include/gconv.h
socket.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
socket.o: /usr/include/bits/stdio_lim.h /usr/include/unistd.h
socket.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
