
default:lib

include ../Makefile.config

O=	zmw.o \
	zmw_graphic.o \
	zmw_drag.o \
	zmw_event.o \
	zmw_main.o \
	zmw_name.o \
	zmw_device.o \
	zmw_state.o \
	zmw_child_cache.o \
	zmw_generated.o \
	zmw_font.o \
	zmw_rectangle.o


lib:: $(O)

