
default:lib

include ../Makefile.config

O=	zmw.o \
	zmw_graphic.o \
	zmw_drag.o \
	zmw_event.o \
	zmw_main.o \
	zmw_name.o \
	zmw_device.o \
	zmw_cache.o \
	zmw_size.o


lib:: $(O)


# DO NOT DELETE
