
/* This file is automaticaly generated by the script zmw-generate.py
 * DO NOT EDIT
*/

#include <zmw/zmw.h>
#include <zmw/zmw_private.h>

Zmw zmw ;

#undef zmw_action_get
int (*zmw_action_get(void))(void) { return zmw.ptr->i.action ; }
#undef zmw_action_get_ptr
int (**zmw_action_get_ptr(void))(void) { return &zmw.ptr->i.action ; }
#undef zmw_action_set
void zmw_action_set(int (*x)(void)) { zmw.ptr->i.action = x ; }
#undef zmw_parent__action_get
int (*zmw_parent__action_get(void))(void) { return (zmw.ptr-1)->i.action ; }
#undef zmw_parent__action_get_ptr
int (**zmw_parent__action_get_ptr(void))(void) { return &(zmw.ptr-1)->i.action ; }
#undef zmw_parent__action_set
void zmw_parent__action_set(int (*x)(void)) { (zmw.ptr-1)->i.action = x ; }
#undef zmw_debug_get
int zmw_debug_get(void) { return zmw.ptr->i.debug ; }
#undef zmw_debug_get_ptr
int *zmw_debug_get_ptr(void) { return &zmw.ptr->i.debug ; }
#undef zmw_debug_set
void zmw_debug_set(const int x) { zmw.ptr->i.debug = x ; }
#undef zmw_parent__debug_get
int zmw_parent__debug_get(void) { return (zmw.ptr-1)->i.debug ; }
#undef zmw_parent__debug_get_ptr
int *zmw_parent__debug_get_ptr(void) { return &(zmw.ptr-1)->i.debug ; }
#undef zmw_parent__debug_set
void zmw_parent__debug_set(const int x) { (zmw.ptr-1)->i.debug = x ; }
#undef zmw_colors_get
int* zmw_colors_get(void) { return zmw.ptr->i.colors ; }
#undef zmw_parent__colors_get
int* zmw_parent__colors_get(void) { return (zmw.ptr-1)->i.colors ; }
#undef zmw_font_family_get
Zmw_Font_Family zmw_font_family_get(void) { return zmw.ptr->i.font.family ; }
#undef zmw_font_family_get_ptr
Zmw_Font_Family *zmw_font_family_get_ptr(void) { return &zmw.ptr->i.font.family ; }
#undef zmw_font_family_set
void zmw_font_family_set(const Zmw_Font_Family x) { zmw.ptr->i.font.family = x ; }
#undef zmw_parent__font_family_get
Zmw_Font_Family zmw_parent__font_family_get(void) { return (zmw.ptr-1)->i.font.family ; }
#undef zmw_parent__font_family_get_ptr
Zmw_Font_Family *zmw_parent__font_family_get_ptr(void) { return &(zmw.ptr-1)->i.font.family ; }
#undef zmw_parent__font_family_set
void zmw_parent__font_family_set(const Zmw_Font_Family x) { (zmw.ptr-1)->i.font.family = x ; }
#undef zmw_font_size_get
Zmw_Font_Size zmw_font_size_get(void) { return zmw.ptr->i.font.size ; }
#undef zmw_font_size_get_ptr
Zmw_Font_Size *zmw_font_size_get_ptr(void) { return &zmw.ptr->i.font.size ; }
#undef zmw_font_size_set
void zmw_font_size_set(const Zmw_Font_Size x) { zmw.ptr->i.font.size = x ; }
#undef zmw_parent__font_size_get
Zmw_Font_Size zmw_parent__font_size_get(void) { return (zmw.ptr-1)->i.font.size ; }
#undef zmw_parent__font_size_get_ptr
Zmw_Font_Size *zmw_parent__font_size_get_ptr(void) { return &(zmw.ptr-1)->i.font.size ; }
#undef zmw_parent__font_size_set
void zmw_parent__font_size_set(const Zmw_Font_Size x) { (zmw.ptr-1)->i.font.size = x ; }
#undef zmw_font_weight_get
Zmw_Font_Weight zmw_font_weight_get(void) { return zmw.ptr->i.font.weight ; }
#undef zmw_font_weight_get_ptr
Zmw_Font_Weight *zmw_font_weight_get_ptr(void) { return &zmw.ptr->i.font.weight ; }
#undef zmw_font_weight_set
void zmw_font_weight_set(const Zmw_Font_Weight x) { zmw.ptr->i.font.weight = x ; }
#undef zmw_parent__font_weight_get
Zmw_Font_Weight zmw_parent__font_weight_get(void) { return (zmw.ptr-1)->i.font.weight ; }
#undef zmw_parent__font_weight_get_ptr
Zmw_Font_Weight *zmw_parent__font_weight_get_ptr(void) { return &(zmw.ptr-1)->i.font.weight ; }
#undef zmw_parent__font_weight_set
void zmw_parent__font_weight_set(const Zmw_Font_Weight x) { (zmw.ptr-1)->i.font.weight = x ; }
#undef zmw_font_style_get
Zmw_Font_Style zmw_font_style_get(void) { return zmw.ptr->i.font.style ; }
#undef zmw_font_style_get_ptr
Zmw_Font_Style *zmw_font_style_get_ptr(void) { return &zmw.ptr->i.font.style ; }
#undef zmw_font_style_set
void zmw_font_style_set(const Zmw_Font_Style x) { zmw.ptr->i.font.style = x ; }
#undef zmw_parent__font_style_get
Zmw_Font_Style zmw_parent__font_style_get(void) { return (zmw.ptr-1)->i.font.style ; }
#undef zmw_parent__font_style_get_ptr
Zmw_Font_Style *zmw_parent__font_style_get_ptr(void) { return &(zmw.ptr-1)->i.font.style ; }
#undef zmw_parent__font_style_set
void zmw_parent__font_style_set(const Zmw_Font_Style x) { (zmw.ptr-1)->i.font.style = x ; }
#undef zmw_font_get
Zmw_Font_Description *zmw_font_get(void) { return &zmw.ptr->i.font ; }
#undef zmw_font_set
void zmw_font_set(const Zmw_Font_Description *x) { zmw.ptr->i.font = *x ; }
#undef zmw_parent__font_get
Zmw_Font_Description *zmw_parent__font_get(void) { return &(zmw.ptr-1)->i.font ; }
#undef zmw_parent__font_set
void zmw_parent__font_set(const Zmw_Font_Description *x) { (zmw.ptr-1)->i.font = *x ; }
#undef zmw_focus_value_get
void* zmw_focus_value_get(void) { return zmw.ptr->i.focus->value ; }
#undef zmw_focus_value_get_ptr
void* *zmw_focus_value_get_ptr(void) { return &zmw.ptr->i.focus->value ; }
#undef zmw_focus_value_set
void zmw_focus_value_set(void* x) { zmw.ptr->i.focus->value = x ; }
#undef zmw_parent__focus_value_get
void* zmw_parent__focus_value_get(void) { return (zmw.ptr-1)->i.focus->value ; }
#undef zmw_parent__focus_value_get_ptr
void* *zmw_parent__focus_value_get_ptr(void) { return &(zmw.ptr-1)->i.focus->value ; }
#undef zmw_parent__focus_value_set
void zmw_parent__focus_value_set(void* x) { (zmw.ptr-1)->i.focus->value = x ; }
#undef zmw_focus_get
Zmw_Name* zmw_focus_get(void) { return zmw.ptr->i.focus ; }
#undef zmw_focus_get_ptr
Zmw_Name* *zmw_focus_get_ptr(void) { return &zmw.ptr->i.focus ; }
#undef zmw_focus_set
void zmw_focus_set(Zmw_Name* x) { zmw.ptr->i.focus = x ; }
#undef zmw_parent__focus_get
Zmw_Name* zmw_parent__focus_get(void) { return (zmw.ptr-1)->i.focus ; }
#undef zmw_parent__focus_get_ptr
Zmw_Name* *zmw_parent__focus_get_ptr(void) { return &(zmw.ptr-1)->i.focus ; }
#undef zmw_parent__focus_set
void zmw_parent__focus_set(Zmw_Name* x) { (zmw.ptr-1)->i.focus = x ; }
#undef zmw_border_width_get
Zmw_Width zmw_border_width_get(void) { return zmw.ptr->i.border_width ; }
#undef zmw_border_width_get_ptr
Zmw_Width *zmw_border_width_get_ptr(void) { return &zmw.ptr->i.border_width ; }
#undef zmw_border_width_set
void zmw_border_width_set(const Zmw_Width x) { zmw.ptr->i.border_width = x ; }
#undef zmw_parent__border_width_get
Zmw_Width zmw_parent__border_width_get(void) { return (zmw.ptr-1)->i.border_width ; }
#undef zmw_parent__border_width_get_ptr
Zmw_Width *zmw_parent__border_width_get_ptr(void) { return &(zmw.ptr-1)->i.border_width ; }
#undef zmw_parent__border_width_set
void zmw_parent__border_width_set(const Zmw_Width x) { (zmw.ptr-1)->i.border_width = x ; }
#undef zmw_focus_width_get
Zmw_Width zmw_focus_width_get(void) { return zmw.ptr->i.focus_width ; }
#undef zmw_focus_width_get_ptr
Zmw_Width *zmw_focus_width_get_ptr(void) { return &zmw.ptr->i.focus_width ; }
#undef zmw_focus_width_set
void zmw_focus_width_set(const Zmw_Width x) { zmw.ptr->i.focus_width = x ; }
#undef zmw_parent__focus_width_get
Zmw_Width zmw_parent__focus_width_get(void) { return (zmw.ptr-1)->i.focus_width ; }
#undef zmw_parent__focus_width_get_ptr
Zmw_Width *zmw_parent__focus_width_get_ptr(void) { return &(zmw.ptr-1)->i.focus_width ; }
#undef zmw_parent__focus_width_set
void zmw_parent__focus_width_set(const Zmw_Width x) { (zmw.ptr-1)->i.focus_width = x ; }
#undef zmw_auto_resize_get
Zmw_Boolean zmw_auto_resize_get(void) { return zmw.ptr->i.auto_resize ; }
#undef zmw_auto_resize_set
void zmw_auto_resize_set(const Zmw_Boolean x) { zmw.ptr->i.auto_resize = x ; }
#undef zmw_parent__auto_resize_get
Zmw_Boolean zmw_parent__auto_resize_get(void) { return (zmw.ptr-1)->i.auto_resize ; }
#undef zmw_parent__auto_resize_set
void zmw_parent__auto_resize_set(const Zmw_Boolean x) { (zmw.ptr-1)->i.auto_resize = x ; }
#undef zmw_sensitive_get
Zmw_Boolean zmw_sensitive_get(void) { return zmw.ptr->i.sensitive ; }
#undef zmw_sensitive_set
void zmw_sensitive_set(const Zmw_Boolean x) { zmw.ptr->i.sensitive = x ; }
#undef zmw_parent__sensitive_get
Zmw_Boolean zmw_parent__sensitive_get(void) { return (zmw.ptr-1)->i.sensitive ; }
#undef zmw_parent__sensitive_set
void zmw_parent__sensitive_set(const Zmw_Boolean x) { (zmw.ptr-1)->i.sensitive = x ; }
#undef zmw_call_number_get
int zmw_call_number_get(void) { return zmw.ptr->u.call_number ; }
#undef zmw_call_number_get_ptr
int *zmw_call_number_get_ptr(void) { return &zmw.ptr->u.call_number ; }
#undef zmw_call_number_set
void zmw_call_number_set(const int x) { zmw.ptr->u.call_number = x ; }
#undef zmw_parent__call_number_get
int zmw_parent__call_number_get(void) { return (zmw.ptr-1)->u.call_number ; }
#undef zmw_parent__call_number_get_ptr
int *zmw_parent__call_number_get_ptr(void) { return &(zmw.ptr-1)->u.call_number ; }
#undef zmw_parent__call_number_set
void zmw_parent__call_number_set(const int x) { (zmw.ptr-1)->u.call_number = x ; }
#undef zmw_name_get
char* zmw_name_get(void) { return zmw.ptr->u.name ; }
#undef zmw_name_get_ptr
char* *zmw_name_get_ptr(void) { return &zmw.ptr->u.name ; }
#undef zmw_name_set
void zmw_name_set(char* x) { zmw.ptr->u.name = x ; }
#undef zmw_parent__name_get
char* zmw_parent__name_get(void) { return (zmw.ptr-1)->u.name ; }
#undef zmw_parent__name_get_ptr
char* *zmw_parent__name_get_ptr(void) { return &(zmw.ptr-1)->u.name ; }
#undef zmw_parent__name_set
void zmw_parent__name_set(char* x) { (zmw.ptr-1)->u.name = x ; }
#undef zmw_name_index_get
char* zmw_name_index_get(void) { return zmw.ptr->u.name_index ; }
#undef zmw_name_index_get_ptr
char* *zmw_name_index_get_ptr(void) { return &zmw.ptr->u.name_index ; }
#undef zmw_name_index_set
void zmw_name_index_set(char* x) { zmw.ptr->u.name_index = x ; }
#undef zmw_parent__name_index_get
char* zmw_parent__name_index_get(void) { return (zmw.ptr-1)->u.name_index ; }
#undef zmw_parent__name_index_get_ptr
char* *zmw_parent__name_index_get_ptr(void) { return &(zmw.ptr-1)->u.name_index ; }
#undef zmw_parent__name_index_set
void zmw_parent__name_index_set(char* x) { (zmw.ptr-1)->u.name_index = x ; }
#undef zmw_name_separator_get
int zmw_name_separator_get(void) { return zmw.ptr->u.name_separator ; }
#undef zmw_name_separator_get_ptr
int *zmw_name_separator_get_ptr(void) { return &zmw.ptr->u.name_separator ; }
#undef zmw_name_separator_set
void zmw_name_separator_set(const int x) { zmw.ptr->u.name_separator = x ; }
#undef zmw_parent__name_separator_get
int zmw_parent__name_separator_get(void) { return (zmw.ptr-1)->u.name_separator ; }
#undef zmw_parent__name_separator_get_ptr
int *zmw_parent__name_separator_get_ptr(void) { return &(zmw.ptr-1)->u.name_separator ; }
#undef zmw_parent__name_separator_set
void zmw_parent__name_separator_set(const int x) { (zmw.ptr-1)->u.name_separator = x ; }
#undef zmw_nb_of_children_get
int zmw_nb_of_children_get(void) { return zmw.ptr->u.nb_of_children ; }
#undef zmw_nb_of_children_get_ptr
int *zmw_nb_of_children_get_ptr(void) { return &zmw.ptr->u.nb_of_children ; }
#undef zmw_nb_of_children_set
void zmw_nb_of_children_set(const int x) { zmw.ptr->u.nb_of_children = x ; }
#undef zmw_parent__nb_of_children_get
int zmw_parent__nb_of_children_get(void) { return (zmw.ptr-1)->u.nb_of_children ; }
#undef zmw_parent__nb_of_children_get_ptr
int *zmw_parent__nb_of_children_get_ptr(void) { return &(zmw.ptr-1)->u.nb_of_children ; }
#undef zmw_parent__nb_of_children_set
void zmw_parent__nb_of_children_set(const int x) { (zmw.ptr-1)->u.nb_of_children = x ; }
#undef zmw_nb_of_children_max_get
int zmw_nb_of_children_max_get(void) { return zmw.ptr->u.nb_of_children_max ; }
#undef zmw_nb_of_children_max_get_ptr
int *zmw_nb_of_children_max_get_ptr(void) { return &zmw.ptr->u.nb_of_children_max ; }
#undef zmw_nb_of_children_max_set
void zmw_nb_of_children_max_set(const int x) { zmw.ptr->u.nb_of_children_max = x ; }
#undef zmw_parent__nb_of_children_max_get
int zmw_parent__nb_of_children_max_get(void) { return (zmw.ptr-1)->u.nb_of_children_max ; }
#undef zmw_parent__nb_of_children_max_get_ptr
int *zmw_parent__nb_of_children_max_get_ptr(void) { return &(zmw.ptr-1)->u.nb_of_children_max ; }
#undef zmw_parent__nb_of_children_max_set
void zmw_parent__nb_of_children_max_set(const int x) { (zmw.ptr-1)->u.nb_of_children_max = x ; }
#undef zmw_children_get
Zmw_Child* zmw_children_get(void) { return zmw.ptr->u.children ; }
#undef zmw_children_get_ptr
Zmw_Child* *zmw_children_get_ptr(void) { return &zmw.ptr->u.children ; }
#undef zmw_children_set
void zmw_children_set(Zmw_Child* x) { zmw.ptr->u.children = x ; }
#undef zmw_parent__children_get
Zmw_Child* zmw_parent__children_get(void) { return (zmw.ptr-1)->u.children ; }
#undef zmw_parent__children_get_ptr
Zmw_Child* *zmw_parent__children_get_ptr(void) { return &(zmw.ptr-1)->u.children ; }
#undef zmw_parent__children_set
void zmw_parent__children_set(Zmw_Child* x) { (zmw.ptr-1)->u.children = x ; }
#undef zmw_do_not_execute_pop_get
Zmw_Boolean zmw_do_not_execute_pop_get(void) { return zmw.ptr->u.do_not_execute_pop ; }
#undef zmw_do_not_execute_pop_set
void zmw_do_not_execute_pop_set(const Zmw_Boolean x) { zmw.ptr->u.do_not_execute_pop = x ; }
#undef zmw_parent__do_not_execute_pop_get
Zmw_Boolean zmw_parent__do_not_execute_pop_get(void) { return (zmw.ptr-1)->u.do_not_execute_pop ; }
#undef zmw_parent__do_not_execute_pop_set
void zmw_parent__do_not_execute_pop_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.do_not_execute_pop = x ; }
#undef zmw_external_state_get
Zmw_External_State zmw_external_state_get(void) { return zmw.ptr->u.external_state ; }
#undef zmw_external_state_get_ptr
Zmw_External_State *zmw_external_state_get_ptr(void) { return &zmw.ptr->u.external_state ; }
#undef zmw_external_state_set
void zmw_external_state_set(const Zmw_External_State x) { zmw.ptr->u.external_state = x ; }
#undef zmw_parent__external_state_get
Zmw_External_State zmw_parent__external_state_get(void) { return (zmw.ptr-1)->u.external_state ; }
#undef zmw_parent__external_state_get_ptr
Zmw_External_State *zmw_parent__external_state_get_ptr(void) { return &(zmw.ptr-1)->u.external_state ; }
#undef zmw_parent__external_state_set
void zmw_parent__external_state_set(const Zmw_External_State x) { (zmw.ptr-1)->u.external_state = x ; }
#undef zmw_asked_width_get
Zmw_Size zmw_asked_width_get(void) { return zmw.ptr->u.asked.width ; }
#undef zmw_asked_width_get_ptr
Zmw_Size *zmw_asked_width_get_ptr(void) { return &zmw.ptr->u.asked.width ; }
#undef zmw_asked_width_set
void zmw_asked_width_set(const Zmw_Size x) { zmw.ptr->u.asked.width = x ; }
#undef zmw_parent__asked_width_get
Zmw_Size zmw_parent__asked_width_get(void) { return (zmw.ptr-1)->u.asked.width ; }
#undef zmw_parent__asked_width_get_ptr
Zmw_Size *zmw_parent__asked_width_get_ptr(void) { return &(zmw.ptr-1)->u.asked.width ; }
#undef zmw_parent__asked_width_set
void zmw_parent__asked_width_set(const Zmw_Size x) { (zmw.ptr-1)->u.asked.width = x ; }
#undef zmw_asked_height_get
Zmw_Size zmw_asked_height_get(void) { return zmw.ptr->u.asked.height ; }
#undef zmw_asked_height_get_ptr
Zmw_Size *zmw_asked_height_get_ptr(void) { return &zmw.ptr->u.asked.height ; }
#undef zmw_asked_height_set
void zmw_asked_height_set(const Zmw_Size x) { zmw.ptr->u.asked.height = x ; }
#undef zmw_parent__asked_height_get
Zmw_Size zmw_parent__asked_height_get(void) { return (zmw.ptr-1)->u.asked.height ; }
#undef zmw_parent__asked_height_get_ptr
Zmw_Size *zmw_parent__asked_height_get_ptr(void) { return &(zmw.ptr-1)->u.asked.height ; }
#undef zmw_parent__asked_height_set
void zmw_parent__asked_height_set(const Zmw_Size x) { (zmw.ptr-1)->u.asked.height = x ; }
#undef zmw_asked_x_get
Zmw_Position zmw_asked_x_get(void) { return zmw.ptr->u.asked.x ; }
#undef zmw_asked_x_get_ptr
Zmw_Position *zmw_asked_x_get_ptr(void) { return &zmw.ptr->u.asked.x ; }
#undef zmw_asked_x_set
void zmw_asked_x_set(const Zmw_Position x) { zmw.ptr->u.asked.x = x ; }
#undef zmw_parent__asked_x_get
Zmw_Position zmw_parent__asked_x_get(void) { return (zmw.ptr-1)->u.asked.x ; }
#undef zmw_parent__asked_x_get_ptr
Zmw_Position *zmw_parent__asked_x_get_ptr(void) { return &(zmw.ptr-1)->u.asked.x ; }
#undef zmw_parent__asked_x_set
void zmw_parent__asked_x_set(const Zmw_Position x) { (zmw.ptr-1)->u.asked.x = x ; }
#undef zmw_asked_y_get
Zmw_Position zmw_asked_y_get(void) { return zmw.ptr->u.asked.y ; }
#undef zmw_asked_y_get_ptr
Zmw_Position *zmw_asked_y_get_ptr(void) { return &zmw.ptr->u.asked.y ; }
#undef zmw_asked_y_set
void zmw_asked_y_set(const Zmw_Position x) { zmw.ptr->u.asked.y = x ; }
#undef zmw_parent__asked_y_get
Zmw_Position zmw_parent__asked_y_get(void) { return (zmw.ptr-1)->u.asked.y ; }
#undef zmw_parent__asked_y_get_ptr
Zmw_Position *zmw_parent__asked_y_get_ptr(void) { return &(zmw.ptr-1)->u.asked.y ; }
#undef zmw_parent__asked_y_set
void zmw_parent__asked_y_set(const Zmw_Position x) { (zmw.ptr-1)->u.asked.y = x ; }
#undef zmw_asked_get
Zmw_Rectangle *zmw_asked_get(void) { return &zmw.ptr->u.asked ; }
#undef zmw_asked_set
void zmw_asked_set(const Zmw_Rectangle *x) { zmw.ptr->u.asked = *x ; }
#undef zmw_parent__asked_get
Zmw_Rectangle *zmw_parent__asked_get(void) { return &(zmw.ptr-1)->u.asked ; }
#undef zmw_parent__asked_set
void zmw_parent__asked_set(const Zmw_Rectangle *x) { (zmw.ptr-1)->u.asked = *x ; }
#undef zmw_type_get
const char* zmw_type_get(void) { return zmw.ptr->u.type ; }
#undef zmw_type_get_ptr
const char* *zmw_type_get_ptr(void) { return &zmw.ptr->u.type ; }
#undef zmw_type_set
void zmw_type_set(const char* x) { zmw.ptr->u.type = x ; }
#undef zmw_parent__type_get
const char* zmw_parent__type_get(void) { return (zmw.ptr-1)->u.type ; }
#undef zmw_parent__type_get_ptr
const char* *zmw_parent__type_get_ptr(void) { return &(zmw.ptr-1)->u.type ; }
#undef zmw_parent__type_set
void zmw_parent__type_set(const char* x) { (zmw.ptr-1)->u.type = x ; }
#undef zmw_file_get
const char* zmw_file_get(void) { return zmw.ptr->u.file ; }
#undef zmw_file_get_ptr
const char* *zmw_file_get_ptr(void) { return &zmw.ptr->u.file ; }
#undef zmw_file_set
void zmw_file_set(const char* x) { zmw.ptr->u.file = x ; }
#undef zmw_parent__file_get
const char* zmw_parent__file_get(void) { return (zmw.ptr-1)->u.file ; }
#undef zmw_parent__file_get_ptr
const char* *zmw_parent__file_get_ptr(void) { return &(zmw.ptr-1)->u.file ; }
#undef zmw_parent__file_set
void zmw_parent__file_set(const char* x) { (zmw.ptr-1)->u.file = x ; }
#undef zmw_line_get
int zmw_line_get(void) { return zmw.ptr->u.line ; }
#undef zmw_line_get_ptr
int *zmw_line_get_ptr(void) { return &zmw.ptr->u.line ; }
#undef zmw_line_set
void zmw_line_set(const int x) { zmw.ptr->u.line = x ; }
#undef zmw_parent__line_get
int zmw_parent__line_get(void) { return (zmw.ptr-1)->u.line ; }
#undef zmw_parent__line_get_ptr
int *zmw_parent__line_get_ptr(void) { return &(zmw.ptr-1)->u.line ; }
#undef zmw_parent__line_set
void zmw_parent__line_set(const int x) { (zmw.ptr-1)->u.line = x ; }
#undef zmw_subaction_get
Zmw_Subaction zmw_subaction_get(void) { return zmw.ptr->u.subaction ; }
#undef zmw_subaction_get_ptr
Zmw_Subaction *zmw_subaction_get_ptr(void) { return &zmw.ptr->u.subaction ; }
#undef zmw_subaction_set
void zmw_subaction_set(const Zmw_Subaction x) { zmw.ptr->u.subaction = x ; }
#undef zmw_parent__subaction_get
Zmw_Subaction zmw_parent__subaction_get(void) { return (zmw.ptr-1)->u.subaction ; }
#undef zmw_parent__subaction_get_ptr
Zmw_Subaction *zmw_parent__subaction_get_ptr(void) { return &(zmw.ptr-1)->u.subaction ; }
#undef zmw_parent__subaction_set
void zmw_parent__subaction_set(const Zmw_Subaction x) { (zmw.ptr-1)->u.subaction = x ; }
#undef zmw_menu_state_get
int* zmw_menu_state_get(void) { return zmw.ptr->u.menu_state ; }
#undef zmw_menu_state_get_ptr
int* *zmw_menu_state_get_ptr(void) { return &zmw.ptr->u.menu_state ; }
#undef zmw_menu_state_set
void zmw_menu_state_set(int* x) { zmw.ptr->u.menu_state = x ; }
#undef zmw_parent__menu_state_get
int* zmw_parent__menu_state_get(void) { return (zmw.ptr-1)->u.menu_state ; }
#undef zmw_parent__menu_state_get_ptr
int* *zmw_parent__menu_state_get_ptr(void) { return &(zmw.ptr-1)->u.menu_state ; }
#undef zmw_parent__menu_state_set
void zmw_parent__menu_state_set(int* x) { (zmw.ptr-1)->u.menu_state = x ; }
#undef zmw_child_number_get
int zmw_child_number_get(void) { return zmw.ptr->u.child_number ; }
#undef zmw_child_number_get_ptr
int *zmw_child_number_get_ptr(void) { return &zmw.ptr->u.child_number ; }
#undef zmw_child_number_set
void zmw_child_number_set(const int x) { zmw.ptr->u.child_number = x ; }
#undef zmw_parent__child_number_get
int zmw_parent__child_number_get(void) { return (zmw.ptr-1)->u.child_number ; }
#undef zmw_parent__child_number_get_ptr
int *zmw_parent__child_number_get_ptr(void) { return &(zmw.ptr-1)->u.child_number ; }
#undef zmw_parent__child_number_set
void zmw_parent__child_number_set(const int x) { (zmw.ptr-1)->u.child_number = x ; }
#undef zmw_window_get
GdkWindow** zmw_window_get(void) { return zmw.ptr->u.parent_to_child.window ; }
#undef zmw_window_get_ptr
GdkWindow** *zmw_window_get_ptr(void) { return &zmw.ptr->u.parent_to_child.window ; }
#undef zmw_window_set
void zmw_window_set(GdkWindow** x) { zmw.ptr->u.parent_to_child.window = x ; }
#undef zmw_parent__window_get
GdkWindow** zmw_parent__window_get(void) { return (zmw.ptr-1)->u.parent_to_child.window ; }
#undef zmw_parent__window_get_ptr
GdkWindow** *zmw_parent__window_get_ptr(void) { return &(zmw.ptr-1)->u.parent_to_child.window ; }
#undef zmw_parent__window_set
void zmw_parent__window_set(GdkWindow** x) { (zmw.ptr-1)->u.parent_to_child.window = x ; }
#undef zmw_gc_get
GdkGC* zmw_gc_get(void) { return zmw.ptr->u.parent_to_child.gc ; }
#undef zmw_gc_get_ptr
GdkGC* *zmw_gc_get_ptr(void) { return &zmw.ptr->u.parent_to_child.gc ; }
#undef zmw_gc_set
void zmw_gc_set(GdkGC* x) { zmw.ptr->u.parent_to_child.gc = x ; }
#undef zmw_parent__gc_get
GdkGC* zmw_parent__gc_get(void) { return (zmw.ptr-1)->u.parent_to_child.gc ; }
#undef zmw_parent__gc_get_ptr
GdkGC* *zmw_parent__gc_get_ptr(void) { return &(zmw.ptr-1)->u.parent_to_child.gc ; }
#undef zmw_parent__gc_set
void zmw_parent__gc_set(GdkGC* x) { (zmw.ptr-1)->u.parent_to_child.gc = x ; }
#undef zmw_clipping_x_get
Zmw_Position zmw_clipping_x_get(void) { return zmw.ptr->u.parent_to_child.clipping.x ; }
#undef zmw_clipping_x_get_ptr
Zmw_Position *zmw_clipping_x_get_ptr(void) { return &zmw.ptr->u.parent_to_child.clipping.x ; }
#undef zmw_clipping_x_set
void zmw_clipping_x_set(const Zmw_Position x) { zmw.ptr->u.parent_to_child.clipping.x = x ; }
#undef zmw_parent__clipping_x_get
Zmw_Position zmw_parent__clipping_x_get(void) { return (zmw.ptr-1)->u.parent_to_child.clipping.x ; }
#undef zmw_parent__clipping_x_get_ptr
Zmw_Position *zmw_parent__clipping_x_get_ptr(void) { return &(zmw.ptr-1)->u.parent_to_child.clipping.x ; }
#undef zmw_parent__clipping_x_set
void zmw_parent__clipping_x_set(const Zmw_Position x) { (zmw.ptr-1)->u.parent_to_child.clipping.x = x ; }
#undef zmw_clipping_y_get
Zmw_Position zmw_clipping_y_get(void) { return zmw.ptr->u.parent_to_child.clipping.y ; }
#undef zmw_clipping_y_get_ptr
Zmw_Position *zmw_clipping_y_get_ptr(void) { return &zmw.ptr->u.parent_to_child.clipping.y ; }
#undef zmw_clipping_y_set
void zmw_clipping_y_set(const Zmw_Position x) { zmw.ptr->u.parent_to_child.clipping.y = x ; }
#undef zmw_parent__clipping_y_get
Zmw_Position zmw_parent__clipping_y_get(void) { return (zmw.ptr-1)->u.parent_to_child.clipping.y ; }
#undef zmw_parent__clipping_y_get_ptr
Zmw_Position *zmw_parent__clipping_y_get_ptr(void) { return &(zmw.ptr-1)->u.parent_to_child.clipping.y ; }
#undef zmw_parent__clipping_y_set
void zmw_parent__clipping_y_set(const Zmw_Position x) { (zmw.ptr-1)->u.parent_to_child.clipping.y = x ; }
#undef zmw_clipping_width_get
Zmw_Size zmw_clipping_width_get(void) { return zmw.ptr->u.parent_to_child.clipping.width ; }
#undef zmw_clipping_width_get_ptr
Zmw_Size *zmw_clipping_width_get_ptr(void) { return &zmw.ptr->u.parent_to_child.clipping.width ; }
#undef zmw_clipping_width_set
void zmw_clipping_width_set(const Zmw_Size x) { zmw.ptr->u.parent_to_child.clipping.width = x ; }
#undef zmw_parent__clipping_width_get
Zmw_Size zmw_parent__clipping_width_get(void) { return (zmw.ptr-1)->u.parent_to_child.clipping.width ; }
#undef zmw_parent__clipping_width_get_ptr
Zmw_Size *zmw_parent__clipping_width_get_ptr(void) { return &(zmw.ptr-1)->u.parent_to_child.clipping.width ; }
#undef zmw_parent__clipping_width_set
void zmw_parent__clipping_width_set(const Zmw_Size x) { (zmw.ptr-1)->u.parent_to_child.clipping.width = x ; }
#undef zmw_clipping_height_get
Zmw_Size zmw_clipping_height_get(void) { return zmw.ptr->u.parent_to_child.clipping.height ; }
#undef zmw_clipping_height_get_ptr
Zmw_Size *zmw_clipping_height_get_ptr(void) { return &zmw.ptr->u.parent_to_child.clipping.height ; }
#undef zmw_clipping_height_set
void zmw_clipping_height_set(const Zmw_Size x) { zmw.ptr->u.parent_to_child.clipping.height = x ; }
#undef zmw_parent__clipping_height_get
Zmw_Size zmw_parent__clipping_height_get(void) { return (zmw.ptr-1)->u.parent_to_child.clipping.height ; }
#undef zmw_parent__clipping_height_get_ptr
Zmw_Size *zmw_parent__clipping_height_get_ptr(void) { return &(zmw.ptr-1)->u.parent_to_child.clipping.height ; }
#undef zmw_parent__clipping_height_set
void zmw_parent__clipping_height_set(const Zmw_Size x) { (zmw.ptr-1)->u.parent_to_child.clipping.height = x ; }
#undef zmw_clipping_get
Zmw_Rectangle *zmw_clipping_get(void) { return &zmw.ptr->u.parent_to_child.clipping ; }
#undef zmw_clipping_set
void zmw_clipping_set(const Zmw_Rectangle *x) { zmw.ptr->u.parent_to_child.clipping = *x ; }
#undef zmw_parent__clipping_get
Zmw_Rectangle *zmw_parent__clipping_get(void) { return &(zmw.ptr-1)->u.parent_to_child.clipping ; }
#undef zmw_parent__clipping_set
void zmw_parent__clipping_set(const Zmw_Rectangle *x) { (zmw.ptr-1)->u.parent_to_child.clipping = *x ; }
#undef zmw_parent_to_child_get
Zmw_Parent_To_Child *zmw_parent_to_child_get(void) { return &zmw.ptr->u.parent_to_child ; }
#undef zmw_parent_to_child_set
void zmw_parent_to_child_set(const Zmw_Parent_To_Child *x) { zmw.ptr->u.parent_to_child = *x ; }
#undef zmw_parent__parent_to_child_get
Zmw_Parent_To_Child *zmw_parent__parent_to_child_get(void) { return &(zmw.ptr-1)->u.parent_to_child ; }
#undef zmw_parent__parent_to_child_set
void zmw_parent__parent_to_child_set(const Zmw_Parent_To_Child *x) { (zmw.ptr-1)->u.parent_to_child = *x ; }
#undef zmw_size_get
Zmw_Child *zmw_size_get(void) { return zmw.ptr->u.size ; }
#undef zmw_size_set
void zmw_size_set(Zmw_Child *x) { *zmw.ptr->u.size = *x ; }
#undef zmw_parent__size_get
Zmw_Child *zmw_parent__size_get(void) { return (zmw.ptr-1)->u.size ; }
#undef zmw_parent__size_set
void zmw_parent__size_set(Zmw_Child *x) { *(zmw.ptr-1)->u.size = *x ; }
#undef zmw_child__size_get
Zmw_Child *zmw_child__size_get(int i) { return (&zmw.ptr->u.children[i]) ; }
#undef zmw_child__size_set
void zmw_child__size_set(int i, Zmw_Child *x) { *(&zmw.ptr->u.children[i]) = *x ; }
#undef zmw_invisible_get
Zmw_Boolean zmw_invisible_get(void) { return zmw.ptr->u.size->invisible ; }
#undef zmw_invisible_set
void zmw_invisible_set(const Zmw_Boolean x) { zmw.ptr->u.size->invisible = x ; }
#undef zmw_parent__invisible_get
Zmw_Boolean zmw_parent__invisible_get(void) { return (zmw.ptr-1)->u.size->invisible ; }
#undef zmw_parent__invisible_set
void zmw_parent__invisible_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->invisible = x ; }
#undef zmw_child__invisible_get
Zmw_Boolean zmw_child__invisible_get(int i) { return (&zmw.ptr->u.children[i])->invisible ; }
#undef zmw_child__invisible_set
void zmw_child__invisible_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->invisible = x ; }
#undef zmw_sensitived_get
Zmw_Boolean zmw_sensitived_get(void) { return zmw.ptr->u.size->sensitived ; }
#undef zmw_sensitived_set
void zmw_sensitived_set(const Zmw_Boolean x) { zmw.ptr->u.size->sensitived = x ; }
#undef zmw_parent__sensitived_get
Zmw_Boolean zmw_parent__sensitived_get(void) { return (zmw.ptr-1)->u.size->sensitived ; }
#undef zmw_parent__sensitived_set
void zmw_parent__sensitived_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->sensitived = x ; }
#undef zmw_child__sensitived_get
Zmw_Boolean zmw_child__sensitived_get(int i) { return (&zmw.ptr->u.children[i])->sensitived ; }
#undef zmw_child__sensitived_set
void zmw_child__sensitived_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->sensitived = x ; }
#undef zmw_pass_through_get
Zmw_Boolean zmw_pass_through_get(void) { return zmw.ptr->u.size->pass_through ; }
#undef zmw_pass_through_set
void zmw_pass_through_set(const Zmw_Boolean x) { zmw.ptr->u.size->pass_through = x ; }
#undef zmw_parent__pass_through_get
Zmw_Boolean zmw_parent__pass_through_get(void) { return (zmw.ptr-1)->u.size->pass_through ; }
#undef zmw_parent__pass_through_set
void zmw_parent__pass_through_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->pass_through = x ; }
#undef zmw_child__pass_through_get
Zmw_Boolean zmw_child__pass_through_get(int i) { return (&zmw.ptr->u.children[i])->pass_through ; }
#undef zmw_child__pass_through_set
void zmw_child__pass_through_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->pass_through = x ; }
#undef zmw_event_in_rectangle_get
Zmw_Boolean zmw_event_in_rectangle_get(void) { return zmw.ptr->u.size->event_in_rectangle ; }
#undef zmw_event_in_rectangle_set
void zmw_event_in_rectangle_set(const Zmw_Boolean x) { zmw.ptr->u.size->event_in_rectangle = x ; }
#undef zmw_parent__event_in_rectangle_get
Zmw_Boolean zmw_parent__event_in_rectangle_get(void) { return (zmw.ptr-1)->u.size->event_in_rectangle ; }
#undef zmw_parent__event_in_rectangle_set
void zmw_parent__event_in_rectangle_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->event_in_rectangle = x ; }
#undef zmw_child__event_in_rectangle_get
Zmw_Boolean zmw_child__event_in_rectangle_get(int i) { return (&zmw.ptr->u.children[i])->event_in_rectangle ; }
#undef zmw_child__event_in_rectangle_set
void zmw_child__event_in_rectangle_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->event_in_rectangle = x ; }
#undef zmw_event_in_children_get
Zmw_Boolean zmw_event_in_children_get(void) { return zmw.ptr->u.size->event_in_children ; }
#undef zmw_event_in_children_set
void zmw_event_in_children_set(const Zmw_Boolean x) { zmw.ptr->u.size->event_in_children = x ; }
#undef zmw_parent__event_in_children_get
Zmw_Boolean zmw_parent__event_in_children_get(void) { return (zmw.ptr-1)->u.size->event_in_children ; }
#undef zmw_parent__event_in_children_set
void zmw_parent__event_in_children_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->event_in_children = x ; }
#undef zmw_child__event_in_children_get
Zmw_Boolean zmw_child__event_in_children_get(int i) { return (&zmw.ptr->u.children[i])->event_in_children ; }
#undef zmw_child__event_in_children_set
void zmw_child__event_in_children_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->event_in_children = x ; }
#undef zmw_allocated_x_get
Zmw_Position zmw_allocated_x_get(void) { return zmw.ptr->u.size->allocated.x ; }
#undef zmw_allocated_x_get_ptr
Zmw_Position *zmw_allocated_x_get_ptr(void) { return &zmw.ptr->u.size->allocated.x ; }
#undef zmw_allocated_x_set
void zmw_allocated_x_set(const Zmw_Position x) { zmw.ptr->u.size->allocated.x = x ; }
#undef zmw_parent__allocated_x_get
Zmw_Position zmw_parent__allocated_x_get(void) { return (zmw.ptr-1)->u.size->allocated.x ; }
#undef zmw_parent__allocated_x_get_ptr
Zmw_Position *zmw_parent__allocated_x_get_ptr(void) { return &(zmw.ptr-1)->u.size->allocated.x ; }
#undef zmw_parent__allocated_x_set
void zmw_parent__allocated_x_set(const Zmw_Position x) { (zmw.ptr-1)->u.size->allocated.x = x ; }
#undef zmw_child__allocated_x_get
Zmw_Position zmw_child__allocated_x_get(int i) { return (&zmw.ptr->u.children[i])->allocated.x ; }
#undef zmw_child__allocated_x_get_ptr
Zmw_Position *zmw_child__allocated_x_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->allocated.x ; }
#undef zmw_child__allocated_x_set
void zmw_child__allocated_x_set(int i, const Zmw_Position x) { (&zmw.ptr->u.children[i])->allocated.x = x ; }
#undef zmw_allocated_y_get
Zmw_Position zmw_allocated_y_get(void) { return zmw.ptr->u.size->allocated.y ; }
#undef zmw_allocated_y_get_ptr
Zmw_Position *zmw_allocated_y_get_ptr(void) { return &zmw.ptr->u.size->allocated.y ; }
#undef zmw_allocated_y_set
void zmw_allocated_y_set(const Zmw_Position x) { zmw.ptr->u.size->allocated.y = x ; }
#undef zmw_parent__allocated_y_get
Zmw_Position zmw_parent__allocated_y_get(void) { return (zmw.ptr-1)->u.size->allocated.y ; }
#undef zmw_parent__allocated_y_get_ptr
Zmw_Position *zmw_parent__allocated_y_get_ptr(void) { return &(zmw.ptr-1)->u.size->allocated.y ; }
#undef zmw_parent__allocated_y_set
void zmw_parent__allocated_y_set(const Zmw_Position x) { (zmw.ptr-1)->u.size->allocated.y = x ; }
#undef zmw_child__allocated_y_get
Zmw_Position zmw_child__allocated_y_get(int i) { return (&zmw.ptr->u.children[i])->allocated.y ; }
#undef zmw_child__allocated_y_get_ptr
Zmw_Position *zmw_child__allocated_y_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->allocated.y ; }
#undef zmw_child__allocated_y_set
void zmw_child__allocated_y_set(int i, const Zmw_Position x) { (&zmw.ptr->u.children[i])->allocated.y = x ; }
#undef zmw_allocated_width_get
Zmw_Size zmw_allocated_width_get(void) { return zmw.ptr->u.size->allocated.width ; }
#undef zmw_allocated_width_get_ptr
Zmw_Size *zmw_allocated_width_get_ptr(void) { return &zmw.ptr->u.size->allocated.width ; }
#undef zmw_allocated_width_set
void zmw_allocated_width_set(const Zmw_Size x) { zmw.ptr->u.size->allocated.width = x ; }
#undef zmw_parent__allocated_width_get
Zmw_Size zmw_parent__allocated_width_get(void) { return (zmw.ptr-1)->u.size->allocated.width ; }
#undef zmw_parent__allocated_width_get_ptr
Zmw_Size *zmw_parent__allocated_width_get_ptr(void) { return &(zmw.ptr-1)->u.size->allocated.width ; }
#undef zmw_parent__allocated_width_set
void zmw_parent__allocated_width_set(const Zmw_Size x) { (zmw.ptr-1)->u.size->allocated.width = x ; }
#undef zmw_child__allocated_width_get
Zmw_Size zmw_child__allocated_width_get(int i) { return (&zmw.ptr->u.children[i])->allocated.width ; }
#undef zmw_child__allocated_width_get_ptr
Zmw_Size *zmw_child__allocated_width_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->allocated.width ; }
#undef zmw_child__allocated_width_set
void zmw_child__allocated_width_set(int i, const Zmw_Size x) { (&zmw.ptr->u.children[i])->allocated.width = x ; }
#undef zmw_allocated_height_get
Zmw_Size zmw_allocated_height_get(void) { return zmw.ptr->u.size->allocated.height ; }
#undef zmw_allocated_height_get_ptr
Zmw_Size *zmw_allocated_height_get_ptr(void) { return &zmw.ptr->u.size->allocated.height ; }
#undef zmw_allocated_height_set
void zmw_allocated_height_set(const Zmw_Size x) { zmw.ptr->u.size->allocated.height = x ; }
#undef zmw_parent__allocated_height_get
Zmw_Size zmw_parent__allocated_height_get(void) { return (zmw.ptr-1)->u.size->allocated.height ; }
#undef zmw_parent__allocated_height_get_ptr
Zmw_Size *zmw_parent__allocated_height_get_ptr(void) { return &(zmw.ptr-1)->u.size->allocated.height ; }
#undef zmw_parent__allocated_height_set
void zmw_parent__allocated_height_set(const Zmw_Size x) { (zmw.ptr-1)->u.size->allocated.height = x ; }
#undef zmw_child__allocated_height_get
Zmw_Size zmw_child__allocated_height_get(int i) { return (&zmw.ptr->u.children[i])->allocated.height ; }
#undef zmw_child__allocated_height_get_ptr
Zmw_Size *zmw_child__allocated_height_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->allocated.height ; }
#undef zmw_child__allocated_height_set
void zmw_child__allocated_height_set(int i, const Zmw_Size x) { (&zmw.ptr->u.children[i])->allocated.height = x ; }
#undef zmw_allocated_get
Zmw_Rectangle *zmw_allocated_get(void) { return &zmw.ptr->u.size->allocated ; }
#undef zmw_allocated_set
void zmw_allocated_set(const Zmw_Rectangle *x) { zmw.ptr->u.size->allocated = *x ; }
#undef zmw_parent__allocated_get
Zmw_Rectangle *zmw_parent__allocated_get(void) { return &(zmw.ptr-1)->u.size->allocated ; }
#undef zmw_parent__allocated_set
void zmw_parent__allocated_set(const Zmw_Rectangle *x) { (zmw.ptr-1)->u.size->allocated = *x ; }
#undef zmw_child__allocated_get
Zmw_Rectangle *zmw_child__allocated_get(int i) { return &(&zmw.ptr->u.children[i])->allocated ; }
#undef zmw_child__allocated_set
void zmw_child__allocated_set(int i, const Zmw_Rectangle *x) { (&zmw.ptr->u.children[i])->allocated = *x ; }
#undef zmw_required_x_get
Zmw_Position zmw_required_x_get(void) { return zmw.ptr->u.size->required.x ; }
#undef zmw_required_x_get_ptr
Zmw_Position *zmw_required_x_get_ptr(void) { return &zmw.ptr->u.size->required.x ; }
#undef zmw_required_x_set
void zmw_required_x_set(const Zmw_Position x) { zmw.ptr->u.size->required.x = x ; }
#undef zmw_parent__required_x_get
Zmw_Position zmw_parent__required_x_get(void) { return (zmw.ptr-1)->u.size->required.x ; }
#undef zmw_parent__required_x_get_ptr
Zmw_Position *zmw_parent__required_x_get_ptr(void) { return &(zmw.ptr-1)->u.size->required.x ; }
#undef zmw_parent__required_x_set
void zmw_parent__required_x_set(const Zmw_Position x) { (zmw.ptr-1)->u.size->required.x = x ; }
#undef zmw_child__required_x_get
Zmw_Position zmw_child__required_x_get(int i) { return (&zmw.ptr->u.children[i])->required.x ; }
#undef zmw_child__required_x_get_ptr
Zmw_Position *zmw_child__required_x_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->required.x ; }
#undef zmw_child__required_x_set
void zmw_child__required_x_set(int i, const Zmw_Position x) { (&zmw.ptr->u.children[i])->required.x = x ; }
#undef zmw_required_y_get
Zmw_Position zmw_required_y_get(void) { return zmw.ptr->u.size->required.y ; }
#undef zmw_required_y_get_ptr
Zmw_Position *zmw_required_y_get_ptr(void) { return &zmw.ptr->u.size->required.y ; }
#undef zmw_required_y_set
void zmw_required_y_set(const Zmw_Position x) { zmw.ptr->u.size->required.y = x ; }
#undef zmw_parent__required_y_get
Zmw_Position zmw_parent__required_y_get(void) { return (zmw.ptr-1)->u.size->required.y ; }
#undef zmw_parent__required_y_get_ptr
Zmw_Position *zmw_parent__required_y_get_ptr(void) { return &(zmw.ptr-1)->u.size->required.y ; }
#undef zmw_parent__required_y_set
void zmw_parent__required_y_set(const Zmw_Position x) { (zmw.ptr-1)->u.size->required.y = x ; }
#undef zmw_child__required_y_get
Zmw_Position zmw_child__required_y_get(int i) { return (&zmw.ptr->u.children[i])->required.y ; }
#undef zmw_child__required_y_get_ptr
Zmw_Position *zmw_child__required_y_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->required.y ; }
#undef zmw_child__required_y_set
void zmw_child__required_y_set(int i, const Zmw_Position x) { (&zmw.ptr->u.children[i])->required.y = x ; }
#undef zmw_required_width_get
Zmw_Size zmw_required_width_get(void) { return zmw.ptr->u.size->required.width ; }
#undef zmw_required_width_get_ptr
Zmw_Size *zmw_required_width_get_ptr(void) { return &zmw.ptr->u.size->required.width ; }
#undef zmw_required_width_set
void zmw_required_width_set(const Zmw_Size x) { zmw.ptr->u.size->required.width = x ; }
#undef zmw_parent__required_width_get
Zmw_Size zmw_parent__required_width_get(void) { return (zmw.ptr-1)->u.size->required.width ; }
#undef zmw_parent__required_width_get_ptr
Zmw_Size *zmw_parent__required_width_get_ptr(void) { return &(zmw.ptr-1)->u.size->required.width ; }
#undef zmw_parent__required_width_set
void zmw_parent__required_width_set(const Zmw_Size x) { (zmw.ptr-1)->u.size->required.width = x ; }
#undef zmw_child__required_width_get
Zmw_Size zmw_child__required_width_get(int i) { return (&zmw.ptr->u.children[i])->required.width ; }
#undef zmw_child__required_width_get_ptr
Zmw_Size *zmw_child__required_width_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->required.width ; }
#undef zmw_child__required_width_set
void zmw_child__required_width_set(int i, const Zmw_Size x) { (&zmw.ptr->u.children[i])->required.width = x ; }
#undef zmw_required_height_get
Zmw_Size zmw_required_height_get(void) { return zmw.ptr->u.size->required.height ; }
#undef zmw_required_height_get_ptr
Zmw_Size *zmw_required_height_get_ptr(void) { return &zmw.ptr->u.size->required.height ; }
#undef zmw_required_height_set
void zmw_required_height_set(const Zmw_Size x) { zmw.ptr->u.size->required.height = x ; }
#undef zmw_parent__required_height_get
Zmw_Size zmw_parent__required_height_get(void) { return (zmw.ptr-1)->u.size->required.height ; }
#undef zmw_parent__required_height_get_ptr
Zmw_Size *zmw_parent__required_height_get_ptr(void) { return &(zmw.ptr-1)->u.size->required.height ; }
#undef zmw_parent__required_height_set
void zmw_parent__required_height_set(const Zmw_Size x) { (zmw.ptr-1)->u.size->required.height = x ; }
#undef zmw_child__required_height_get
Zmw_Size zmw_child__required_height_get(int i) { return (&zmw.ptr->u.children[i])->required.height ; }
#undef zmw_child__required_height_get_ptr
Zmw_Size *zmw_child__required_height_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->required.height ; }
#undef zmw_child__required_height_set
void zmw_child__required_height_set(int i, const Zmw_Size x) { (&zmw.ptr->u.children[i])->required.height = x ; }
#undef zmw_required_get
Zmw_Rectangle *zmw_required_get(void) { return &zmw.ptr->u.size->required ; }
#undef zmw_required_set
void zmw_required_set(const Zmw_Rectangle *x) { zmw.ptr->u.size->required = *x ; }
#undef zmw_parent__required_get
Zmw_Rectangle *zmw_parent__required_get(void) { return &(zmw.ptr-1)->u.size->required ; }
#undef zmw_parent__required_set
void zmw_parent__required_set(const Zmw_Rectangle *x) { (zmw.ptr-1)->u.size->required = *x ; }
#undef zmw_child__required_get
Zmw_Rectangle *zmw_child__required_get(int i) { return &(&zmw.ptr->u.children[i])->required ; }
#undef zmw_child__required_set
void zmw_child__required_set(int i, const Zmw_Rectangle *x) { (&zmw.ptr->u.children[i])->required = *x ; }
#undef zmw_min_x_get
Zmw_Position zmw_min_x_get(void) { return zmw.ptr->u.size->min.x ; }
#undef zmw_min_x_get_ptr
Zmw_Position *zmw_min_x_get_ptr(void) { return &zmw.ptr->u.size->min.x ; }
#undef zmw_min_x_set
void zmw_min_x_set(const Zmw_Position x) { zmw.ptr->u.size->min.x = x ; }
#undef zmw_parent__min_x_get
Zmw_Position zmw_parent__min_x_get(void) { return (zmw.ptr-1)->u.size->min.x ; }
#undef zmw_parent__min_x_get_ptr
Zmw_Position *zmw_parent__min_x_get_ptr(void) { return &(zmw.ptr-1)->u.size->min.x ; }
#undef zmw_parent__min_x_set
void zmw_parent__min_x_set(const Zmw_Position x) { (zmw.ptr-1)->u.size->min.x = x ; }
#undef zmw_child__min_x_get
Zmw_Position zmw_child__min_x_get(int i) { return (&zmw.ptr->u.children[i])->min.x ; }
#undef zmw_child__min_x_get_ptr
Zmw_Position *zmw_child__min_x_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->min.x ; }
#undef zmw_child__min_x_set
void zmw_child__min_x_set(int i, const Zmw_Position x) { (&zmw.ptr->u.children[i])->min.x = x ; }
#undef zmw_min_y_get
Zmw_Position zmw_min_y_get(void) { return zmw.ptr->u.size->min.y ; }
#undef zmw_min_y_get_ptr
Zmw_Position *zmw_min_y_get_ptr(void) { return &zmw.ptr->u.size->min.y ; }
#undef zmw_min_y_set
void zmw_min_y_set(const Zmw_Position x) { zmw.ptr->u.size->min.y = x ; }
#undef zmw_parent__min_y_get
Zmw_Position zmw_parent__min_y_get(void) { return (zmw.ptr-1)->u.size->min.y ; }
#undef zmw_parent__min_y_get_ptr
Zmw_Position *zmw_parent__min_y_get_ptr(void) { return &(zmw.ptr-1)->u.size->min.y ; }
#undef zmw_parent__min_y_set
void zmw_parent__min_y_set(const Zmw_Position x) { (zmw.ptr-1)->u.size->min.y = x ; }
#undef zmw_child__min_y_get
Zmw_Position zmw_child__min_y_get(int i) { return (&zmw.ptr->u.children[i])->min.y ; }
#undef zmw_child__min_y_get_ptr
Zmw_Position *zmw_child__min_y_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->min.y ; }
#undef zmw_child__min_y_set
void zmw_child__min_y_set(int i, const Zmw_Position x) { (&zmw.ptr->u.children[i])->min.y = x ; }
#undef zmw_min_width_get
Zmw_Size zmw_min_width_get(void) { return zmw.ptr->u.size->min.width ; }
#undef zmw_min_width_get_ptr
Zmw_Size *zmw_min_width_get_ptr(void) { return &zmw.ptr->u.size->min.width ; }
#undef zmw_min_width_set
void zmw_min_width_set(const Zmw_Size x) { zmw.ptr->u.size->min.width = x ; }
#undef zmw_parent__min_width_get
Zmw_Size zmw_parent__min_width_get(void) { return (zmw.ptr-1)->u.size->min.width ; }
#undef zmw_parent__min_width_get_ptr
Zmw_Size *zmw_parent__min_width_get_ptr(void) { return &(zmw.ptr-1)->u.size->min.width ; }
#undef zmw_parent__min_width_set
void zmw_parent__min_width_set(const Zmw_Size x) { (zmw.ptr-1)->u.size->min.width = x ; }
#undef zmw_child__min_width_get
Zmw_Size zmw_child__min_width_get(int i) { return (&zmw.ptr->u.children[i])->min.width ; }
#undef zmw_child__min_width_get_ptr
Zmw_Size *zmw_child__min_width_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->min.width ; }
#undef zmw_child__min_width_set
void zmw_child__min_width_set(int i, const Zmw_Size x) { (&zmw.ptr->u.children[i])->min.width = x ; }
#undef zmw_min_height_get
Zmw_Size zmw_min_height_get(void) { return zmw.ptr->u.size->min.height ; }
#undef zmw_min_height_get_ptr
Zmw_Size *zmw_min_height_get_ptr(void) { return &zmw.ptr->u.size->min.height ; }
#undef zmw_min_height_set
void zmw_min_height_set(const Zmw_Size x) { zmw.ptr->u.size->min.height = x ; }
#undef zmw_parent__min_height_get
Zmw_Size zmw_parent__min_height_get(void) { return (zmw.ptr-1)->u.size->min.height ; }
#undef zmw_parent__min_height_get_ptr
Zmw_Size *zmw_parent__min_height_get_ptr(void) { return &(zmw.ptr-1)->u.size->min.height ; }
#undef zmw_parent__min_height_set
void zmw_parent__min_height_set(const Zmw_Size x) { (zmw.ptr-1)->u.size->min.height = x ; }
#undef zmw_child__min_height_get
Zmw_Size zmw_child__min_height_get(int i) { return (&zmw.ptr->u.children[i])->min.height ; }
#undef zmw_child__min_height_get_ptr
Zmw_Size *zmw_child__min_height_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->min.height ; }
#undef zmw_child__min_height_set
void zmw_child__min_height_set(int i, const Zmw_Size x) { (&zmw.ptr->u.children[i])->min.height = x ; }
#undef zmw_min_get
Zmw_Rectangle *zmw_min_get(void) { return &zmw.ptr->u.size->min ; }
#undef zmw_min_set
void zmw_min_set(const Zmw_Rectangle *x) { zmw.ptr->u.size->min = *x ; }
#undef zmw_parent__min_get
Zmw_Rectangle *zmw_parent__min_get(void) { return &(zmw.ptr-1)->u.size->min ; }
#undef zmw_parent__min_set
void zmw_parent__min_set(const Zmw_Rectangle *x) { (zmw.ptr-1)->u.size->min = *x ; }
#undef zmw_child__min_get
Zmw_Rectangle *zmw_child__min_get(int i) { return &(&zmw.ptr->u.children[i])->min ; }
#undef zmw_child__min_set
void zmw_child__min_set(int i, const Zmw_Rectangle *x) { (&zmw.ptr->u.children[i])->min = *x ; }
#undef zmw_focused_get
Zmw_Boolean zmw_focused_get(void) { return zmw.ptr->u.size->focused ; }
#undef zmw_focused_set
void zmw_focused_set(const Zmw_Boolean x) { zmw.ptr->u.size->focused = x ; }
#undef zmw_parent__focused_get
Zmw_Boolean zmw_parent__focused_get(void) { return (zmw.ptr-1)->u.size->focused ; }
#undef zmw_parent__focused_set
void zmw_parent__focused_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->focused = x ; }
#undef zmw_child__focused_get
Zmw_Boolean zmw_child__focused_get(int i) { return (&zmw.ptr->u.children[i])->focused ; }
#undef zmw_child__focused_set
void zmw_child__focused_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->focused = x ; }
#undef zmw_activated_get
Zmw_Boolean zmw_activated_get(void) { return zmw.ptr->u.size->activated ; }
#undef zmw_activated_set
void zmw_activated_set(const Zmw_Boolean x) { zmw.ptr->u.size->activated = x ; }
#undef zmw_parent__activated_get
Zmw_Boolean zmw_parent__activated_get(void) { return (zmw.ptr-1)->u.size->activated ; }
#undef zmw_parent__activated_set
void zmw_parent__activated_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->activated = x ; }
#undef zmw_child__activated_get
Zmw_Boolean zmw_child__activated_get(int i) { return (&zmw.ptr->u.children[i])->activated ; }
#undef zmw_child__activated_set
void zmw_child__activated_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->activated = x ; }
#undef zmw_children_activated_get
Zmw_Boolean zmw_children_activated_get(void) { return zmw.ptr->u.size->children_activated ; }
#undef zmw_children_activated_set
void zmw_children_activated_set(const Zmw_Boolean x) { zmw.ptr->u.size->children_activated = x ; }
#undef zmw_parent__children_activated_get
Zmw_Boolean zmw_parent__children_activated_get(void) { return (zmw.ptr-1)->u.size->children_activated ; }
#undef zmw_parent__children_activated_set
void zmw_parent__children_activated_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->children_activated = x ; }
#undef zmw_child__children_activated_get
Zmw_Boolean zmw_child__children_activated_get(int i) { return (&zmw.ptr->u.children[i])->children_activated ; }
#undef zmw_child__children_activated_set
void zmw_child__children_activated_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->children_activated = x ; }
#undef zmw_changed_get
Zmw_Boolean zmw_changed_get(void) { return zmw.ptr->u.size->changed ; }
#undef zmw_changed_set
void zmw_changed_set(const Zmw_Boolean x) { zmw.ptr->u.size->changed = x ; }
#undef zmw_parent__changed_get
Zmw_Boolean zmw_parent__changed_get(void) { return (zmw.ptr-1)->u.size->changed ; }
#undef zmw_parent__changed_set
void zmw_parent__changed_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->changed = x ; }
#undef zmw_child__changed_get
Zmw_Boolean zmw_child__changed_get(int i) { return (&zmw.ptr->u.children[i])->changed ; }
#undef zmw_child__changed_set
void zmw_child__changed_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->changed = x ; }
#undef zmw_tip_visible_get
Zmw_Boolean zmw_tip_visible_get(void) { return zmw.ptr->u.size->tip_visible ; }
#undef zmw_tip_visible_set
void zmw_tip_visible_set(const Zmw_Boolean x) { zmw.ptr->u.size->tip_visible = x ; }
#undef zmw_parent__tip_visible_get
Zmw_Boolean zmw_parent__tip_visible_get(void) { return (zmw.ptr-1)->u.size->tip_visible ; }
#undef zmw_parent__tip_visible_set
void zmw_parent__tip_visible_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->tip_visible = x ; }
#undef zmw_child__tip_visible_get
Zmw_Boolean zmw_child__tip_visible_get(int i) { return (&zmw.ptr->u.children[i])->tip_visible ; }
#undef zmw_child__tip_visible_set
void zmw_child__tip_visible_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->tip_visible = x ; }
#undef zmw_hash_key_get
Zmw_Hash zmw_hash_key_get(void) { return zmw.ptr->u.size->hash_key ; }
#undef zmw_hash_key_get_ptr
Zmw_Hash *zmw_hash_key_get_ptr(void) { return &zmw.ptr->u.size->hash_key ; }
#undef zmw_hash_key_set
void zmw_hash_key_set(const Zmw_Hash x) { zmw.ptr->u.size->hash_key = x ; }
#undef zmw_parent__hash_key_get
Zmw_Hash zmw_parent__hash_key_get(void) { return (zmw.ptr-1)->u.size->hash_key ; }
#undef zmw_parent__hash_key_get_ptr
Zmw_Hash *zmw_parent__hash_key_get_ptr(void) { return &(zmw.ptr-1)->u.size->hash_key ; }
#undef zmw_parent__hash_key_set
void zmw_parent__hash_key_set(const Zmw_Hash x) { (zmw.ptr-1)->u.size->hash_key = x ; }
#undef zmw_child__hash_key_get
Zmw_Hash zmw_child__hash_key_get(int i) { return (&zmw.ptr->u.children[i])->hash_key ; }
#undef zmw_child__hash_key_get_ptr
Zmw_Hash *zmw_child__hash_key_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->hash_key ; }
#undef zmw_child__hash_key_set
void zmw_child__hash_key_set(int i, const Zmw_Hash x) { (&zmw.ptr->u.children[i])->hash_key = x ; }
#undef zmw_do_not_map_window_get
Zmw_Boolean zmw_do_not_map_window_get(void) { return zmw.ptr->u.size->do_not_map_window ; }
#undef zmw_do_not_map_window_set
void zmw_do_not_map_window_set(const Zmw_Boolean x) { zmw.ptr->u.size->do_not_map_window = x ; }
#undef zmw_parent__do_not_map_window_get
Zmw_Boolean zmw_parent__do_not_map_window_get(void) { return (zmw.ptr-1)->u.size->do_not_map_window ; }
#undef zmw_parent__do_not_map_window_set
void zmw_parent__do_not_map_window_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->do_not_map_window = x ; }
#undef zmw_child__do_not_map_window_get
Zmw_Boolean zmw_child__do_not_map_window_get(int i) { return (&zmw.ptr->u.children[i])->do_not_map_window ; }
#undef zmw_child__do_not_map_window_set
void zmw_child__do_not_map_window_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->do_not_map_window = x ; }
#undef zmw_used_by_parent_get
Zmw_Boolean zmw_used_by_parent_get(void) { return zmw.ptr->u.size->used_by_parent ; }
#undef zmw_used_by_parent_set
void zmw_used_by_parent_set(const Zmw_Boolean x) { zmw.ptr->u.size->used_by_parent = x ; }
#undef zmw_parent__used_by_parent_get
Zmw_Boolean zmw_parent__used_by_parent_get(void) { return (zmw.ptr-1)->u.size->used_by_parent ; }
#undef zmw_parent__used_by_parent_set
void zmw_parent__used_by_parent_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->used_by_parent = x ; }
#undef zmw_child__used_by_parent_get
Zmw_Boolean zmw_child__used_by_parent_get(int i) { return (&zmw.ptr->u.children[i])->used_by_parent ; }
#undef zmw_child__used_by_parent_set
void zmw_child__used_by_parent_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->used_by_parent = x ; }
#undef zmw_horizontaly_expanded_get
Zmw_Boolean zmw_horizontaly_expanded_get(void) { return zmw.ptr->u.size->horizontaly_expanded ; }
#undef zmw_horizontaly_expanded_set
void zmw_horizontaly_expanded_set(const Zmw_Boolean x) { zmw.ptr->u.size->horizontaly_expanded = x ; }
#undef zmw_parent__horizontaly_expanded_get
Zmw_Boolean zmw_parent__horizontaly_expanded_get(void) { return (zmw.ptr-1)->u.size->horizontaly_expanded ; }
#undef zmw_parent__horizontaly_expanded_set
void zmw_parent__horizontaly_expanded_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->horizontaly_expanded = x ; }
#undef zmw_child__horizontaly_expanded_get
Zmw_Boolean zmw_child__horizontaly_expanded_get(int i) { return (&zmw.ptr->u.children[i])->horizontaly_expanded ; }
#undef zmw_child__horizontaly_expanded_set
void zmw_child__horizontaly_expanded_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->horizontaly_expanded = x ; }
#undef zmw_verticaly_expanded_get
Zmw_Boolean zmw_verticaly_expanded_get(void) { return zmw.ptr->u.size->verticaly_expanded ; }
#undef zmw_verticaly_expanded_set
void zmw_verticaly_expanded_set(const Zmw_Boolean x) { zmw.ptr->u.size->verticaly_expanded = x ; }
#undef zmw_parent__verticaly_expanded_get
Zmw_Boolean zmw_parent__verticaly_expanded_get(void) { return (zmw.ptr-1)->u.size->verticaly_expanded ; }
#undef zmw_parent__verticaly_expanded_set
void zmw_parent__verticaly_expanded_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->verticaly_expanded = x ; }
#undef zmw_child__verticaly_expanded_get
Zmw_Boolean zmw_child__verticaly_expanded_get(int i) { return (&zmw.ptr->u.children[i])->verticaly_expanded ; }
#undef zmw_child__verticaly_expanded_set
void zmw_child__verticaly_expanded_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->verticaly_expanded = x ; }
#undef zmw_horizontal_expand_get
Zmw_Boolean zmw_horizontal_expand_get(void) { return zmw.ptr->u.size->current_state.horizontal_expand ; }
#undef zmw_horizontal_expand_set
void zmw_horizontal_expand_set(const Zmw_Boolean x) { zmw.ptr->u.size->current_state.horizontal_expand = x ; }
#undef zmw_parent__horizontal_expand_get
Zmw_Boolean zmw_parent__horizontal_expand_get(void) { return (zmw.ptr-1)->u.size->current_state.horizontal_expand ; }
#undef zmw_parent__horizontal_expand_set
void zmw_parent__horizontal_expand_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->current_state.horizontal_expand = x ; }
#undef zmw_child__horizontal_expand_get
Zmw_Boolean zmw_child__horizontal_expand_get(int i) { return (&zmw.ptr->u.children[i])->current_state.horizontal_expand ; }
#undef zmw_child__horizontal_expand_set
void zmw_child__horizontal_expand_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->current_state.horizontal_expand = x ; }
#undef zmw_vertical_expand_get
Zmw_Boolean zmw_vertical_expand_get(void) { return zmw.ptr->u.size->current_state.vertical_expand ; }
#undef zmw_vertical_expand_set
void zmw_vertical_expand_set(const Zmw_Boolean x) { zmw.ptr->u.size->current_state.vertical_expand = x ; }
#undef zmw_parent__vertical_expand_get
Zmw_Boolean zmw_parent__vertical_expand_get(void) { return (zmw.ptr-1)->u.size->current_state.vertical_expand ; }
#undef zmw_parent__vertical_expand_set
void zmw_parent__vertical_expand_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size->current_state.vertical_expand = x ; }
#undef zmw_child__vertical_expand_get
Zmw_Boolean zmw_child__vertical_expand_get(int i) { return (&zmw.ptr->u.children[i])->current_state.vertical_expand ; }
#undef zmw_child__vertical_expand_set
void zmw_child__vertical_expand_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])->current_state.vertical_expand = x ; }
#undef zmw_padding_width_get
Zmw_Width zmw_padding_width_get(void) { return zmw.ptr->u.size->current_state.padding_width ; }
#undef zmw_padding_width_get_ptr
Zmw_Width *zmw_padding_width_get_ptr(void) { return &zmw.ptr->u.size->current_state.padding_width ; }
#undef zmw_padding_width_set
void zmw_padding_width_set(const Zmw_Width x) { zmw.ptr->u.size->current_state.padding_width = x ; }
#undef zmw_parent__padding_width_get
Zmw_Width zmw_parent__padding_width_get(void) { return (zmw.ptr-1)->u.size->current_state.padding_width ; }
#undef zmw_parent__padding_width_get_ptr
Zmw_Width *zmw_parent__padding_width_get_ptr(void) { return &(zmw.ptr-1)->u.size->current_state.padding_width ; }
#undef zmw_parent__padding_width_set
void zmw_parent__padding_width_set(const Zmw_Width x) { (zmw.ptr-1)->u.size->current_state.padding_width = x ; }
#undef zmw_child__padding_width_get
Zmw_Width zmw_child__padding_width_get(int i) { return (&zmw.ptr->u.children[i])->current_state.padding_width ; }
#undef zmw_child__padding_width_get_ptr
Zmw_Width *zmw_child__padding_width_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->current_state.padding_width ; }
#undef zmw_child__padding_width_set
void zmw_child__padding_width_set(int i, const Zmw_Width x) { (&zmw.ptr->u.children[i])->current_state.padding_width = x ; }
#undef zmw_horizontal_alignment_get
Zmw_Alignment zmw_horizontal_alignment_get(void) { return zmw.ptr->u.size->current_state.horizontal_alignment ; }
#undef zmw_horizontal_alignment_get_ptr
Zmw_Alignment *zmw_horizontal_alignment_get_ptr(void) { return &zmw.ptr->u.size->current_state.horizontal_alignment ; }
#undef zmw_horizontal_alignment_set
void zmw_horizontal_alignment_set(const Zmw_Alignment x) { zmw.ptr->u.size->current_state.horizontal_alignment = x ; }
#undef zmw_parent__horizontal_alignment_get
Zmw_Alignment zmw_parent__horizontal_alignment_get(void) { return (zmw.ptr-1)->u.size->current_state.horizontal_alignment ; }
#undef zmw_parent__horizontal_alignment_get_ptr
Zmw_Alignment *zmw_parent__horizontal_alignment_get_ptr(void) { return &(zmw.ptr-1)->u.size->current_state.horizontal_alignment ; }
#undef zmw_parent__horizontal_alignment_set
void zmw_parent__horizontal_alignment_set(const Zmw_Alignment x) { (zmw.ptr-1)->u.size->current_state.horizontal_alignment = x ; }
#undef zmw_child__horizontal_alignment_get
Zmw_Alignment zmw_child__horizontal_alignment_get(int i) { return (&zmw.ptr->u.children[i])->current_state.horizontal_alignment ; }
#undef zmw_child__horizontal_alignment_get_ptr
Zmw_Alignment *zmw_child__horizontal_alignment_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->current_state.horizontal_alignment ; }
#undef zmw_child__horizontal_alignment_set
void zmw_child__horizontal_alignment_set(int i, const Zmw_Alignment x) { (&zmw.ptr->u.children[i])->current_state.horizontal_alignment = x ; }
#undef zmw_vertical_alignment_get
Zmw_Alignment zmw_vertical_alignment_get(void) { return zmw.ptr->u.size->current_state.vertical_alignment ; }
#undef zmw_vertical_alignment_get_ptr
Zmw_Alignment *zmw_vertical_alignment_get_ptr(void) { return &zmw.ptr->u.size->current_state.vertical_alignment ; }
#undef zmw_vertical_alignment_set
void zmw_vertical_alignment_set(const Zmw_Alignment x) { zmw.ptr->u.size->current_state.vertical_alignment = x ; }
#undef zmw_parent__vertical_alignment_get
Zmw_Alignment zmw_parent__vertical_alignment_get(void) { return (zmw.ptr-1)->u.size->current_state.vertical_alignment ; }
#undef zmw_parent__vertical_alignment_get_ptr
Zmw_Alignment *zmw_parent__vertical_alignment_get_ptr(void) { return &(zmw.ptr-1)->u.size->current_state.vertical_alignment ; }
#undef zmw_parent__vertical_alignment_set
void zmw_parent__vertical_alignment_set(const Zmw_Alignment x) { (zmw.ptr-1)->u.size->current_state.vertical_alignment = x ; }
#undef zmw_child__vertical_alignment_get
Zmw_Alignment zmw_child__vertical_alignment_get(int i) { return (&zmw.ptr->u.children[i])->current_state.vertical_alignment ; }
#undef zmw_child__vertical_alignment_get_ptr
Zmw_Alignment *zmw_child__vertical_alignment_get_ptr(int i) { return &(&zmw.ptr->u.children[i])->current_state.vertical_alignment ; }
#undef zmw_child__vertical_alignment_set
void zmw_child__vertical_alignment_set(int i, const Zmw_Alignment x) { (&zmw.ptr->u.children[i])->current_state.vertical_alignment = x ; }
#undef zmw_current_state_get
Zmw_Child_Current_State *zmw_current_state_get(void) { return &zmw.ptr->u.size->current_state ; }
#undef zmw_current_state_set
void zmw_current_state_set(const Zmw_Child_Current_State *x) { zmw.ptr->u.size->current_state = *x ; }
#undef zmw_parent__current_state_get
Zmw_Child_Current_State *zmw_parent__current_state_get(void) { return &(zmw.ptr-1)->u.size->current_state ; }
#undef zmw_parent__current_state_set
void zmw_parent__current_state_set(const Zmw_Child_Current_State *x) { (zmw.ptr-1)->u.size->current_state = *x ; }
#undef zmw_child__current_state_get
Zmw_Child_Current_State *zmw_child__current_state_get(int i) { return &(&zmw.ptr->u.children[i])->current_state ; }
#undef zmw_child__current_state_set
void zmw_child__current_state_set(int i, const Zmw_Child_Current_State *x) { (&zmw.ptr->u.children[i])->current_state = *x ; }
#undef zmw_cs_horizontal_expand_get
Zmw_Boolean zmw_cs_horizontal_expand_get(void) { return zmw.ptr->u.size[1].current_state.horizontal_expand ; }
#undef zmw_cs_horizontal_expand_set
void zmw_cs_horizontal_expand_set(const Zmw_Boolean x) { zmw.ptr->u.size[1].current_state.horizontal_expand = x ; }
#undef zmw_parent__cs_horizontal_expand_get
Zmw_Boolean zmw_parent__cs_horizontal_expand_get(void) { return (zmw.ptr-1)->u.size[1].current_state.horizontal_expand ; }
#undef zmw_parent__cs_horizontal_expand_set
void zmw_parent__cs_horizontal_expand_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size[1].current_state.horizontal_expand = x ; }
#undef zmw_child__cs_horizontal_expand_get
Zmw_Boolean zmw_child__cs_horizontal_expand_get(int i) { return (&zmw.ptr->u.children[i])[1].current_state.horizontal_expand ; }
#undef zmw_child__cs_horizontal_expand_set
void zmw_child__cs_horizontal_expand_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])[1].current_state.horizontal_expand = x ; }
#undef zmw_cs_vertical_expand_get
Zmw_Boolean zmw_cs_vertical_expand_get(void) { return zmw.ptr->u.size[1].current_state.vertical_expand ; }
#undef zmw_cs_vertical_expand_set
void zmw_cs_vertical_expand_set(const Zmw_Boolean x) { zmw.ptr->u.size[1].current_state.vertical_expand = x ; }
#undef zmw_parent__cs_vertical_expand_get
Zmw_Boolean zmw_parent__cs_vertical_expand_get(void) { return (zmw.ptr-1)->u.size[1].current_state.vertical_expand ; }
#undef zmw_parent__cs_vertical_expand_set
void zmw_parent__cs_vertical_expand_set(const Zmw_Boolean x) { (zmw.ptr-1)->u.size[1].current_state.vertical_expand = x ; }
#undef zmw_child__cs_vertical_expand_get
Zmw_Boolean zmw_child__cs_vertical_expand_get(int i) { return (&zmw.ptr->u.children[i])[1].current_state.vertical_expand ; }
#undef zmw_child__cs_vertical_expand_set
void zmw_child__cs_vertical_expand_set(int i, const Zmw_Boolean x) { (&zmw.ptr->u.children[i])[1].current_state.vertical_expand = x ; }
#undef zmw_cs_padding_width_get
Zmw_Width zmw_cs_padding_width_get(void) { return zmw.ptr->u.size[1].current_state.padding_width ; }
#undef zmw_cs_padding_width_get_ptr
Zmw_Width *zmw_cs_padding_width_get_ptr(void) { return &zmw.ptr->u.size[1].current_state.padding_width ; }
#undef zmw_cs_padding_width_set
void zmw_cs_padding_width_set(const Zmw_Width x) { zmw.ptr->u.size[1].current_state.padding_width = x ; }
#undef zmw_parent__cs_padding_width_get
Zmw_Width zmw_parent__cs_padding_width_get(void) { return (zmw.ptr-1)->u.size[1].current_state.padding_width ; }
#undef zmw_parent__cs_padding_width_get_ptr
Zmw_Width *zmw_parent__cs_padding_width_get_ptr(void) { return &(zmw.ptr-1)->u.size[1].current_state.padding_width ; }
#undef zmw_parent__cs_padding_width_set
void zmw_parent__cs_padding_width_set(const Zmw_Width x) { (zmw.ptr-1)->u.size[1].current_state.padding_width = x ; }
#undef zmw_child__cs_padding_width_get
Zmw_Width zmw_child__cs_padding_width_get(int i) { return (&zmw.ptr->u.children[i])[1].current_state.padding_width ; }
#undef zmw_child__cs_padding_width_get_ptr
Zmw_Width *zmw_child__cs_padding_width_get_ptr(int i) { return &(&zmw.ptr->u.children[i])[1].current_state.padding_width ; }
#undef zmw_child__cs_padding_width_set
void zmw_child__cs_padding_width_set(int i, const Zmw_Width x) { (&zmw.ptr->u.children[i])[1].current_state.padding_width = x ; }
#undef zmw_cs_horizontal_alignment_get
Zmw_Alignment zmw_cs_horizontal_alignment_get(void) { return zmw.ptr->u.size[1].current_state.horizontal_alignment ; }
#undef zmw_cs_horizontal_alignment_get_ptr
Zmw_Alignment *zmw_cs_horizontal_alignment_get_ptr(void) { return &zmw.ptr->u.size[1].current_state.horizontal_alignment ; }
#undef zmw_cs_horizontal_alignment_set
void zmw_cs_horizontal_alignment_set(const Zmw_Alignment x) { zmw.ptr->u.size[1].current_state.horizontal_alignment = x ; }
#undef zmw_parent__cs_horizontal_alignment_get
Zmw_Alignment zmw_parent__cs_horizontal_alignment_get(void) { return (zmw.ptr-1)->u.size[1].current_state.horizontal_alignment ; }
#undef zmw_parent__cs_horizontal_alignment_get_ptr
Zmw_Alignment *zmw_parent__cs_horizontal_alignment_get_ptr(void) { return &(zmw.ptr-1)->u.size[1].current_state.horizontal_alignment ; }
#undef zmw_parent__cs_horizontal_alignment_set
void zmw_parent__cs_horizontal_alignment_set(const Zmw_Alignment x) { (zmw.ptr-1)->u.size[1].current_state.horizontal_alignment = x ; }
#undef zmw_child__cs_horizontal_alignment_get
Zmw_Alignment zmw_child__cs_horizontal_alignment_get(int i) { return (&zmw.ptr->u.children[i])[1].current_state.horizontal_alignment ; }
#undef zmw_child__cs_horizontal_alignment_get_ptr
Zmw_Alignment *zmw_child__cs_horizontal_alignment_get_ptr(int i) { return &(&zmw.ptr->u.children[i])[1].current_state.horizontal_alignment ; }
#undef zmw_child__cs_horizontal_alignment_set
void zmw_child__cs_horizontal_alignment_set(int i, const Zmw_Alignment x) { (&zmw.ptr->u.children[i])[1].current_state.horizontal_alignment = x ; }
#undef zmw_cs_vertical_alignment_get
Zmw_Alignment zmw_cs_vertical_alignment_get(void) { return zmw.ptr->u.size[1].current_state.vertical_alignment ; }
#undef zmw_cs_vertical_alignment_get_ptr
Zmw_Alignment *zmw_cs_vertical_alignment_get_ptr(void) { return &zmw.ptr->u.size[1].current_state.vertical_alignment ; }
#undef zmw_cs_vertical_alignment_set
void zmw_cs_vertical_alignment_set(const Zmw_Alignment x) { zmw.ptr->u.size[1].current_state.vertical_alignment = x ; }
#undef zmw_parent__cs_vertical_alignment_get
Zmw_Alignment zmw_parent__cs_vertical_alignment_get(void) { return (zmw.ptr-1)->u.size[1].current_state.vertical_alignment ; }
#undef zmw_parent__cs_vertical_alignment_get_ptr
Zmw_Alignment *zmw_parent__cs_vertical_alignment_get_ptr(void) { return &(zmw.ptr-1)->u.size[1].current_state.vertical_alignment ; }
#undef zmw_parent__cs_vertical_alignment_set
void zmw_parent__cs_vertical_alignment_set(const Zmw_Alignment x) { (zmw.ptr-1)->u.size[1].current_state.vertical_alignment = x ; }
#undef zmw_child__cs_vertical_alignment_get
Zmw_Alignment zmw_child__cs_vertical_alignment_get(int i) { return (&zmw.ptr->u.children[i])[1].current_state.vertical_alignment ; }
#undef zmw_child__cs_vertical_alignment_get_ptr
Zmw_Alignment *zmw_child__cs_vertical_alignment_get_ptr(int i) { return &(&zmw.ptr->u.children[i])[1].current_state.vertical_alignment ; }
#undef zmw_child__cs_vertical_alignment_set
void zmw_child__cs_vertical_alignment_set(int i, const Zmw_Alignment x) { (&zmw.ptr->u.children[i])[1].current_state.vertical_alignment = x ; }
#undef zmw_cs_current_state_get
Zmw_Child_Current_State *zmw_cs_current_state_get(void) { return &zmw.ptr->u.size[1].current_state ; }
#undef zmw_cs_current_state_set
void zmw_cs_current_state_set(const Zmw_Child_Current_State *x) { zmw.ptr->u.size[1].current_state = *x ; }
#undef zmw_parent__cs_current_state_get
Zmw_Child_Current_State *zmw_parent__cs_current_state_get(void) { return &(zmw.ptr-1)->u.size[1].current_state ; }
#undef zmw_parent__cs_current_state_set
void zmw_parent__cs_current_state_set(const Zmw_Child_Current_State *x) { (zmw.ptr-1)->u.size[1].current_state = *x ; }
#undef zmw_child__cs_current_state_get
Zmw_Child_Current_State *zmw_child__cs_current_state_get(int i) { return &(&zmw.ptr->u.children[i])[1].current_state ; }
#undef zmw_child__cs_current_state_set
void zmw_child__cs_current_state_set(int i, const Zmw_Child_Current_State *x) { (&zmw.ptr->u.children[i])[1].current_state = *x ; }
#undef zmw_state_get
Zmw_State* zmw_state_get(void) { return zmw.ptr ; }
#undef zmw_state_get_ptr
Zmw_State* *zmw_state_get_ptr(void) { return &zmw.ptr ; }
#undef zmw_state_set
void zmw_state_set(Zmw_State* x) { zmw.ptr = x ; }
#undef zmw_zmw_full_name_get
char* zmw_zmw_full_name_get(void) { return zmw.full_name ; }
#undef zmw_zmw_table_get
Zmw_State* zmw_zmw_table_get(void) { return zmw.table ; }
#undef zmw_zmw_table_get_ptr
Zmw_State* *zmw_zmw_table_get_ptr(void) { return &zmw.table ; }
#undef zmw_zmw_table_set
void zmw_zmw_table_set(Zmw_State* x) { zmw.table = x ; }
#if ZMW_DEBUG_INSIDE_ZMW_PARAMETER
#undef zmw_zmw_inside_zmw_parameter_get
Zmw_Boolean zmw_zmw_inside_zmw_parameter_get(void) { return zmw.inside_zmw_parameter ; }
#else
#endif
#if ZMW_DEBUG_INSIDE_ZMW_PARAMETER
#undef zmw_zmw_inside_zmw_parameter_set
void zmw_zmw_inside_zmw_parameter_set(const Zmw_Boolean x) { zmw.inside_zmw_parameter = x ; }
#else
#endif
#if ZMW_PROFILING
#undef zmw_zmw_profiling_displayed_get
Zmw_Boolean zmw_zmw_profiling_displayed_get(void) { return zmw.profiling_displayed ; }
#else
#endif
#if ZMW_PROFILING
#undef zmw_zmw_profiling_displayed_set
void zmw_zmw_profiling_displayed_set(const Zmw_Boolean x) { zmw.profiling_displayed = x ; }
#else
#endif
#undef zmw_zmw_event_get
GdkEvent* zmw_zmw_event_get(void) { return zmw.event ; }
#undef zmw_zmw_event_get_ptr
GdkEvent* *zmw_zmw_event_get_ptr(void) { return &zmw.event ; }
#undef zmw_zmw_event_set
void zmw_zmw_event_set(GdkEvent* x) { zmw.event = x ; }
#undef zmw_zmw_x_get
Zmw_Position zmw_zmw_x_get(void) { return zmw.x ; }
#undef zmw_zmw_x_get_ptr
Zmw_Position *zmw_zmw_x_get_ptr(void) { return &zmw.x ; }
#undef zmw_zmw_x_set
void zmw_zmw_x_set(const Zmw_Position x) { zmw.x = x ; }
#undef zmw_zmw_y_get
Zmw_Position zmw_zmw_y_get(void) { return zmw.y ; }
#undef zmw_zmw_y_get_ptr
Zmw_Position *zmw_zmw_y_get_ptr(void) { return &zmw.y ; }
#undef zmw_zmw_y_set
void zmw_zmw_y_set(const Zmw_Position x) { zmw.y = x ; }
#undef zmw_zmw_x_root_get
Zmw_Position zmw_zmw_x_root_get(void) { return zmw.x_root ; }
#undef zmw_zmw_x_root_get_ptr
Zmw_Position *zmw_zmw_x_root_get_ptr(void) { return &zmw.x_root ; }
#undef zmw_zmw_x_root_set
void zmw_zmw_x_root_set(const Zmw_Position x) { zmw.x_root = x ; }
#undef zmw_zmw_y_root_get
Zmw_Position zmw_zmw_y_root_get(void) { return zmw.y_root ; }
#undef zmw_zmw_y_root_get_ptr
Zmw_Position *zmw_zmw_y_root_get_ptr(void) { return &zmw.y_root ; }
#undef zmw_zmw_y_root_set
void zmw_zmw_y_root_set(const Zmw_Position x) { zmw.y_root = x ; }
#undef zmw_zmw_found_get
Zmw_Name *zmw_zmw_found_get(void) { return &zmw.found ; }
#undef zmw_zmw_found_set
void zmw_zmw_found_set(const Zmw_Name *x) { zmw.found = *x ; }
#undef zmw_zmw_widget_to_trace_get
Zmw_Name *zmw_zmw_widget_to_trace_get(void) { return &zmw.widget_to_trace ; }
#undef zmw_zmw_widget_to_trace_set
void zmw_zmw_widget_to_trace_set(const Zmw_Name *x) { zmw.widget_to_trace = *x ; }
#undef zmw_zmw_windows_get
GdkWindow **zmw_zmw_windows_get(void) { return zmw.windows ; }
#undef zmw_zmw_windows_get_ptr
GdkWindow ***zmw_zmw_windows_get_ptr(void) { return &zmw.windows ; }
#undef zmw_zmw_windows_set
void zmw_zmw_windows_set(GdkWindow **x) { zmw.windows = x ; }
#undef zmw_zmw_nb_windows_get
int zmw_zmw_nb_windows_get(void) { return zmw.nb_windows ; }
#undef zmw_zmw_nb_windows_get_ptr
int *zmw_zmw_nb_windows_get_ptr(void) { return &zmw.nb_windows ; }
#undef zmw_zmw_nb_windows_set
void zmw_zmw_nb_windows_set(const int x) { zmw.nb_windows = x ; }
#undef zmw_zmw_window_get
GdkWindow *zmw_zmw_window_get(void) { return zmw.window ; }
#undef zmw_zmw_window_get_ptr
GdkWindow **zmw_zmw_window_get_ptr(void) { return &zmw.window ; }
#undef zmw_zmw_window_set
void zmw_zmw_window_set(GdkWindow *x) { zmw.window = x ; }
#undef zmw_zmw_raised_get
GdkWindow *zmw_zmw_raised_get(void) { return zmw.raised ; }
#undef zmw_zmw_raised_get_ptr
GdkWindow **zmw_zmw_raised_get_ptr(void) { return &zmw.raised ; }
#undef zmw_zmw_raised_set
void zmw_zmw_raised_set(GdkWindow *x) { zmw.raised = x ; }
#undef zmw_zmw_event_removed_get
Zmw_Boolean zmw_zmw_event_removed_get(void) { return zmw.event_removed ; }
#undef zmw_zmw_event_removed_set
void zmw_zmw_event_removed_set(const Zmw_Boolean x) { zmw.event_removed = x ; }
#undef zmw_zmw_focus_with_cursor_value_get
void *zmw_zmw_focus_with_cursor_value_get(void) { return zmw.focus_with_cursor->value ; }
#undef zmw_zmw_focus_with_cursor_value_get_ptr
void **zmw_zmw_focus_with_cursor_value_get_ptr(void) { return &zmw.focus_with_cursor->value ; }
#undef zmw_zmw_focus_with_cursor_value_set
void zmw_zmw_focus_with_cursor_value_set(void *x) { zmw.focus_with_cursor->value = x ; }
#undef zmw_zmw_focus_with_cursor_get
Zmw_Name *zmw_zmw_focus_with_cursor_get(void) { return zmw.focus_with_cursor ; }
#undef zmw_zmw_focus_with_cursor_get_ptr
Zmw_Name **zmw_zmw_focus_with_cursor_get_ptr(void) { return &zmw.focus_with_cursor ; }
#undef zmw_zmw_focus_with_cursor_set
void zmw_zmw_focus_with_cursor_set(Zmw_Name *x) { zmw.focus_with_cursor = x ; }
#undef zmw_zmw_focused_x_get
Zmw_Position zmw_zmw_focused_x_get(void) { return zmw.focused.x ; }
#undef zmw_zmw_focused_x_get_ptr
Zmw_Position *zmw_zmw_focused_x_get_ptr(void) { return &zmw.focused.x ; }
#undef zmw_zmw_focused_x_set
void zmw_zmw_focused_x_set(const Zmw_Position x) { zmw.focused.x = x ; }
#undef zmw_zmw_focused_y_get
Zmw_Position zmw_zmw_focused_y_get(void) { return zmw.focused.y ; }
#undef zmw_zmw_focused_y_get_ptr
Zmw_Position *zmw_zmw_focused_y_get_ptr(void) { return &zmw.focused.y ; }
#undef zmw_zmw_focused_y_set
void zmw_zmw_focused_y_set(const Zmw_Position x) { zmw.focused.y = x ; }
#undef zmw_zmw_focused_width_get
Zmw_Size zmw_zmw_focused_width_get(void) { return zmw.focused.width ; }
#undef zmw_zmw_focused_width_get_ptr
Zmw_Size *zmw_zmw_focused_width_get_ptr(void) { return &zmw.focused.width ; }
#undef zmw_zmw_focused_width_set
void zmw_zmw_focused_width_set(const Zmw_Size x) { zmw.focused.width = x ; }
#undef zmw_zmw_focused_height_get
Zmw_Size zmw_zmw_focused_height_get(void) { return zmw.focused.height ; }
#undef zmw_zmw_focused_height_get_ptr
Zmw_Size *zmw_zmw_focused_height_get_ptr(void) { return &zmw.focused.height ; }
#undef zmw_zmw_focused_height_set
void zmw_zmw_focused_height_set(const Zmw_Size x) { zmw.focused.height = x ; }
#undef zmw_zmw_focused_get
Zmw_Rectangle *zmw_zmw_focused_get(void) { return &zmw.focused ; }
#undef zmw_zmw_focused_set
void zmw_zmw_focused_set(const Zmw_Rectangle *x) { zmw.focused = *x ; }
#undef zmw_zmw_still_yet_displayed_get
Zmw_Boolean zmw_zmw_still_yet_displayed_get(void) { return zmw.still_yet_displayed ; }
#undef zmw_zmw_still_yet_displayed_set
void zmw_zmw_still_yet_displayed_set(const Zmw_Boolean x) { zmw.still_yet_displayed = x ; }
#undef zmw_zmw_button_pressed_get
Zmw_Boolean zmw_zmw_button_pressed_get(void) { return zmw.button_pressed ; }
#undef zmw_zmw_button_pressed_set
void zmw_zmw_button_pressed_set(const Zmw_Boolean x) { zmw.button_pressed = x ; }
#undef zmw_zmw_key_pressed_get
Zmw_Boolean zmw_zmw_key_pressed_get(void) { return zmw.key_pressed ; }
#undef zmw_zmw_key_pressed_set
void zmw_zmw_key_pressed_set(const Zmw_Boolean x) { zmw.key_pressed = x ; }
#undef zmw_zmw_tip_displayed_get
Zmw_Name *zmw_zmw_tip_displayed_get(void) { return &zmw.tip_displayed ; }
#undef zmw_zmw_tip_displayed_set
void zmw_zmw_tip_displayed_set(const Zmw_Name *x) { zmw.tip_displayed = *x ; }
#undef zmw_zmw_tips_yet_displayed_get
Zmw_Boolean zmw_zmw_tips_yet_displayed_get(void) { return zmw.tips_yet_displayed ; }
#undef zmw_zmw_tips_yet_displayed_set
void zmw_zmw_tips_yet_displayed_set(const Zmw_Boolean x) { zmw.tips_yet_displayed = x ; }
#undef zmw_zmw_external_do_not_make_init_get
Zmw_Boolean zmw_zmw_external_do_not_make_init_get(void) { return zmw.external_do_not_make_init ; }
#undef zmw_zmw_external_do_not_make_init_set
void zmw_zmw_external_do_not_make_init_set(const Zmw_Boolean x) { zmw.external_do_not_make_init = x ; }
