O=\
	zmw_notebook.o \
	zmw_box.o \
	zmw_text.o \
	zmw_button.o \
	zmw_toggle.o \
	zmw_scrollbar.o \
	zmw_viewport.o \
	zmw_scrolled_view.o \
	zmw_anchor.o \
	zmw_filechooser.o \
	zmw_alert.o \
	zmw_image.o \
	zmw_message.o \
	zmw_window.o \
	zmw_decorator.o \
	zmw_table.o

lib:: $(O)

include ../Makefile.config

# DO NOT DELETE
