O=\
	zmw_notebook.o \
	zmw_box.o \
	zmw_text.o \
	zmw_toggle.o \
	zmw_scrollbar.o \
	zmw_viewport.o \
	zmw_anchor.o \
	zmw_filechooser.o \
	zmw_alert.o \
	zmw_image.o \
	zmw_message.o \
	zmw_window.o


local_all: widgets.a

widgets.a: $(O)
	ar -r $@ $(O)

include ../Makefile

# DO NOT DELETE

zmw_alert.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_alert.o: /usr/include/gtk-1.2/gdk/gdktypes.h /usr/include/glib-1.2/glib.h
zmw_alert.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_alert.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_alert.o: /usr/include/gnu/stubs.h
zmw_alert.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_alert.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_alert.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_alert.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_alert.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_alert.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_alert.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_alert.o: /usr/include/stdio.h
zmw_alert.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_alert.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_alert.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_alert.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_alert.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_alert.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_alert.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_alert.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_alert.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_anchor.o: /usr/include/gtk-1.2/gdk/gdkkeysyms.h ../kernel/zmw.h
zmw_anchor.o: /usr/include/gtk-1.2/gdk/gdk.h
zmw_anchor.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_anchor.o: /usr/include/glib-1.2/glib.h /usr/lib/glib/include/glibconfig.h
zmw_anchor.o: /usr/include/limits.h /usr/include/features.h
zmw_anchor.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
zmw_anchor.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_anchor.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_anchor.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_anchor.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_anchor.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_anchor.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_anchor.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_anchor.o: /usr/include/stdio.h
zmw_anchor.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_anchor.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_anchor.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_anchor.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_anchor.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_anchor.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_anchor.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_anchor.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_anchor.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_box.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_box.o: /usr/include/gtk-1.2/gdk/gdktypes.h /usr/include/glib-1.2/glib.h
zmw_box.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_box.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_box.o: /usr/include/gnu/stubs.h
zmw_box.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_box.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_box.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_box.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_box.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_box.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_box.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_box.o: /usr/include/stdio.h
zmw_box.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_box.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_box.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_box.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_box.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_box.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_box.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_box.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_box.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_filechooser.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_filechooser.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_filechooser.o: /usr/include/glib-1.2/glib.h
zmw_filechooser.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_filechooser.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_filechooser.o: /usr/include/gnu/stubs.h
zmw_filechooser.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_filechooser.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_filechooser.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_filechooser.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_filechooser.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_filechooser.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_filechooser.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_filechooser.o: /usr/include/stdio.h
zmw_filechooser.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_filechooser.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_filechooser.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_filechooser.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_filechooser.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_filechooser.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_filechooser.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_filechooser.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_filechooser.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_filechooser.o: /usr/include/dirent.h /usr/include/bits/dirent.h
zmw_filechooser.o: /usr/include/sys/stat.h /usr/include/bits/stat.h
zmw_filechooser.o: /usr/include/errno.h /usr/include/bits/errno.h
zmw_filechooser.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
zmw_image.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_image.o: /usr/include/gtk-1.2/gdk/gdktypes.h /usr/include/glib-1.2/glib.h
zmw_image.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_image.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_image.o: /usr/include/gnu/stubs.h
zmw_image.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_image.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_image.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_image.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_image.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_image.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_image.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_image.o: /usr/include/stdio.h
zmw_image.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_image.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_image.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_image.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_image.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_image.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_image.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_image.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_image.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_message.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_message.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_message.o: /usr/include/glib-1.2/glib.h
zmw_message.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_message.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_message.o: /usr/include/gnu/stubs.h
zmw_message.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_message.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_message.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_message.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_message.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_message.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_message.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_message.o: /usr/include/stdio.h
zmw_message.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_message.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_message.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_message.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_message.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_message.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_message.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_message.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_message.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_notebook.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_notebook.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_notebook.o: /usr/include/glib-1.2/glib.h
zmw_notebook.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_notebook.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_notebook.o: /usr/include/gnu/stubs.h
zmw_notebook.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_notebook.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_notebook.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_notebook.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_notebook.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_notebook.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_notebook.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_notebook.o: /usr/include/stdio.h
zmw_notebook.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_notebook.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_notebook.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_notebook.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_notebook.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_notebook.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_notebook.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_notebook.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_notebook.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_scrollbar.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_scrollbar.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_scrollbar.o: /usr/include/glib-1.2/glib.h
zmw_scrollbar.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_scrollbar.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_scrollbar.o: /usr/include/gnu/stubs.h
zmw_scrollbar.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_scrollbar.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_scrollbar.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_scrollbar.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_scrollbar.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_scrollbar.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_scrollbar.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_scrollbar.o: /usr/include/stdio.h
zmw_scrollbar.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_scrollbar.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_scrollbar.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_scrollbar.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_scrollbar.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_scrollbar.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_scrollbar.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_scrollbar.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_scrollbar.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_text.o: /usr/include/gtk-1.2/gdk/gdkkeysyms.h ../kernel/zmw.h
zmw_text.o: /usr/include/gtk-1.2/gdk/gdk.h
zmw_text.o: /usr/include/gtk-1.2/gdk/gdktypes.h /usr/include/glib-1.2/glib.h
zmw_text.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_text.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_text.o: /usr/include/gnu/stubs.h
zmw_text.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_text.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_text.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_text.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_text.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_text.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_text.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_text.o: /usr/include/stdio.h
zmw_text.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_text.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_text.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_text.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_text.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_text.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_text.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_text.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_text.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_toggle.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_toggle.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_toggle.o: /usr/include/glib-1.2/glib.h /usr/lib/glib/include/glibconfig.h
zmw_toggle.o: /usr/include/limits.h /usr/include/features.h
zmw_toggle.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
zmw_toggle.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_toggle.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_toggle.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_toggle.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_toggle.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_toggle.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_toggle.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_toggle.o: /usr/include/stdio.h
zmw_toggle.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_toggle.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_toggle.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_toggle.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_toggle.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_toggle.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_toggle.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_toggle.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_toggle.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_viewport.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_viewport.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_viewport.o: /usr/include/glib-1.2/glib.h
zmw_viewport.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
zmw_viewport.o: /usr/include/features.h /usr/include/sys/cdefs.h
zmw_viewport.o: /usr/include/gnu/stubs.h
zmw_viewport.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_viewport.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_viewport.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_viewport.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_viewport.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_viewport.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_viewport.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_viewport.o: /usr/include/stdio.h
zmw_viewport.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_viewport.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_viewport.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_viewport.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_viewport.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_viewport.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_viewport.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_viewport.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_viewport.o: /usr/include/string.h ../widgets/zmw_widgets.h
zmw_window.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
zmw_window.o: /usr/include/gtk-1.2/gdk/gdktypes.h
zmw_window.o: /usr/include/glib-1.2/glib.h /usr/lib/glib/include/glibconfig.h
zmw_window.o: /usr/include/limits.h /usr/include/features.h
zmw_window.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
zmw_window.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
zmw_window.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
zmw_window.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
zmw_window.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
zmw_window.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
zmw_window.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
zmw_window.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
zmw_window.o: /usr/include/stdio.h
zmw_window.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
zmw_window.o: /usr/include/bits/types.h /usr/include/libio.h
zmw_window.o: /usr/include/_G_config.h /usr/include/wchar.h
zmw_window.o: /usr/include/bits/wchar.h /usr/include/gconv.h
zmw_window.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
zmw_window.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
zmw_window.o: /usr/include/stdlib.h /usr/include/unistd.h
zmw_window.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
zmw_window.o: /usr/include/string.h ../widgets/zmw_widgets.h
