run:circuit
	circuit

local_all::circuit

circuit:circuit_gui.o circuit_application.o ../widgets/widgets.a ../kernel/kernel.a ../utilities/utilities.a
	$(CC) $(CFLAGS) circuit_gui.o circuit_application.o $(OBJS) -o $@

local_clean::
	@-rm circuit 2>/dev/null
	@-rm -r PNG/.xvpics 2>/dev/null

include ../Makefile

# DO NOT DELETE

circuit_application.o: /usr/include/stdio.h /usr/include/features.h
circuit_application.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
circuit_application.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
circuit_application.o: /usr/include/bits/types.h /usr/include/libio.h
circuit_application.o: /usr/include/_G_config.h /usr/include/wchar.h
circuit_application.o: /usr/include/bits/wchar.h /usr/include/gconv.h
circuit_application.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
circuit_application.o: /usr/include/bits/stdio_lim.h /usr/include/stdlib.h
circuit_application.o: /usr/include/string.h circuit_application.h
circuit_gui.o: /usr/include/errno.h /usr/include/features.h
circuit_gui.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
circuit_gui.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
circuit_gui.o: /usr/include/asm/errno.h ../kernel/zmw.h
circuit_gui.o: /usr/include/gtk-1.2/gdk/gdk.h
circuit_gui.o: /usr/include/gtk-1.2/gdk/gdktypes.h
circuit_gui.o: /usr/include/glib-1.2/glib.h
circuit_gui.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
circuit_gui.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
circuit_gui.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
circuit_gui.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
circuit_gui.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
circuit_gui.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
circuit_gui.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
circuit_gui.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
circuit_gui.o: /usr/include/stdio.h
circuit_gui.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
circuit_gui.o: /usr/include/bits/types.h /usr/include/libio.h
circuit_gui.o: /usr/include/_G_config.h /usr/include/wchar.h
circuit_gui.o: /usr/include/bits/wchar.h /usr/include/gconv.h
circuit_gui.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
circuit_gui.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
circuit_gui.o: /usr/include/stdlib.h /usr/include/unistd.h
circuit_gui.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
circuit_gui.o: /usr/include/string.h ../widgets/zmw_widgets.h
circuit_gui.o: circuit_application.h
demo_file_tree.o: ../kernel/zmw.h /usr/include/gtk-1.2/gdk/gdk.h
demo_file_tree.o: /usr/include/gtk-1.2/gdk/gdktypes.h
demo_file_tree.o: /usr/include/glib-1.2/glib.h
demo_file_tree.o: /usr/lib/glib/include/glibconfig.h /usr/include/limits.h
demo_file_tree.o: /usr/include/features.h /usr/include/sys/cdefs.h
demo_file_tree.o: /usr/include/gnu/stubs.h
demo_file_tree.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/limits.h
demo_file_tree.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/float.h
demo_file_tree.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stdarg.h
demo_file_tree.o: /usr/include/gtk-1.2/gdk/gdkcursors.h
demo_file_tree.o: /usr/include/gtk-1.2/gdk/gdkrgb.h
demo_file_tree.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf.h
demo_file_tree.o: /usr/include/gdk-pixbuf-1.0/gdk-pixbuf/gdk-pixbuf-features.h
demo_file_tree.o: /usr/include/stdio.h
demo_file_tree.o: /usr/lib/gcc-lib/i386-linux/2.95.4/include/stddef.h
demo_file_tree.o: /usr/include/bits/types.h /usr/include/libio.h
demo_file_tree.o: /usr/include/_G_config.h /usr/include/wchar.h
demo_file_tree.o: /usr/include/bits/wchar.h /usr/include/gconv.h
demo_file_tree.o: /usr/include/bits/stdio_lim.h /usr/include/setjmp.h
demo_file_tree.o: /usr/include/bits/setjmp.h /usr/include/bits/sigset.h
demo_file_tree.o: /usr/include/stdlib.h /usr/include/unistd.h
demo_file_tree.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
demo_file_tree.o: /usr/include/string.h ../widgets/zmw_widgets.h
demo_file_tree.o: /usr/include/search.h
