accel.o: accel.c
anchor_box.o: anchor_box.c
animation.o: animation.c
asked.o: asked.c
button.o: button.c
color.o: color.c
compose.o: compose.c
cursorin.o: cursorin.c
drag_and_drop.o: drag_and_drop.c
dragger.o: dragger.c
editable_text.o: editable_text.c
embeded.o: embeded.c
expand.o: expand.c
filechooser.o: filechooser.c
focus.o: focus.c
hello_world.o: hello_world.c
hor_hor_box.o: hor_hor_box.c
horizontal_box.o: horizontal_box.c
image.o: image.c
main.o: main.c /home/exco/zmw/include/zmw/zmw.h \
  /usr/include/gtk-2.0/gdk/gdk.h \
  /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h \
  /usr/include/glib-2.0/gio/gio.h /usr/include/glib-2.0/gio/giotypes.h \
  /usr/include/glib-2.0/gio/gioenums.h \
  /usr/include/glib-2.0/glib-object.h \
  /usr/include/glib-2.0/gobject/gboxed.h \
  /usr/include/glib-2.0/gobject/gtype.h /usr/include/glib-2.0/glib.h \
  /usr/include/glib-2.0/glib/galloca.h \
  /usr/include/glib-2.0/glib/gtypes.h \
  /usr/lib/glib-2.0/include/glibconfig.h \
  /usr/include/glib-2.0/glib/gmacros.h \
  /usr/include/glib-2.0/glib/garray.h \
  /usr/include/glib-2.0/glib/gasyncqueue.h \
  /usr/include/glib-2.0/glib/gthread.h \
  /usr/include/glib-2.0/glib/gerror.h /usr/include/glib-2.0/glib/gquark.h \
  /usr/include/glib-2.0/glib/gutils.h \
  /usr/include/glib-2.0/glib/gatomic.h \
  /usr/include/glib-2.0/glib/gbacktrace.h \
  /usr/include/glib-2.0/glib/gbase64.h \
  /usr/include/glib-2.0/glib/gbookmarkfile.h \
  /usr/include/glib-2.0/glib/gcache.h /usr/include/glib-2.0/glib/glist.h \
  /usr/include/glib-2.0/glib/gmem.h /usr/include/glib-2.0/glib/gslice.h \
  /usr/include/glib-2.0/glib/gchecksum.h \
  /usr/include/glib-2.0/glib/gcompletion.h \
  /usr/include/glib-2.0/glib/gconvert.h \
  /usr/include/glib-2.0/glib/gdataset.h \
  /usr/include/glib-2.0/glib/gdate.h /usr/include/glib-2.0/glib/gdir.h \
  /usr/include/glib-2.0/glib/gfileutils.h \
  /usr/include/glib-2.0/glib/ghash.h /usr/include/glib-2.0/glib/ghook.h \
  /usr/include/glib-2.0/glib/giochannel.h \
  /usr/include/glib-2.0/glib/gmain.h /usr/include/glib-2.0/glib/gslist.h \
  /usr/include/glib-2.0/glib/gstring.h \
  /usr/include/glib-2.0/glib/gunicode.h \
  /usr/include/glib-2.0/glib/gkeyfile.h \
  /usr/include/glib-2.0/glib/gmappedfile.h \
  /usr/include/glib-2.0/glib/gmarkup.h \
  /usr/include/glib-2.0/glib/gmessages.h \
  /usr/include/glib-2.0/glib/gnode.h /usr/include/glib-2.0/glib/goption.h \
  /usr/include/glib-2.0/glib/gpattern.h \
  /usr/include/glib-2.0/glib/gprimes.h \
  /usr/include/glib-2.0/glib/gqsort.h /usr/include/glib-2.0/glib/gqueue.h \
  /usr/include/glib-2.0/glib/grand.h /usr/include/glib-2.0/glib/grel.h \
  /usr/include/glib-2.0/glib/gregex.h \
  /usr/include/glib-2.0/glib/gscanner.h \
  /usr/include/glib-2.0/glib/gsequence.h \
  /usr/include/glib-2.0/glib/gshell.h /usr/include/glib-2.0/glib/gspawn.h \
  /usr/include/glib-2.0/glib/gstrfuncs.h \
  /usr/include/glib-2.0/glib/gtestutils.h \
  /usr/include/glib-2.0/glib/gthreadpool.h \
  /usr/include/glib-2.0/glib/gtimer.h /usr/include/glib-2.0/glib/gtree.h \
  /usr/include/glib-2.0/glib/gurifuncs.h \
  /usr/include/glib-2.0/gobject/genums.h \
  /usr/include/glib-2.0/gobject/gobject.h \
  /usr/include/glib-2.0/gobject/gvalue.h \
  /usr/include/glib-2.0/gobject/gparam.h \
  /usr/include/glib-2.0/gobject/gclosure.h \
  /usr/include/glib-2.0/gobject/gsignal.h \
  /usr/include/glib-2.0/gobject/gmarshal.h \
  /usr/include/glib-2.0/gobject/gparamspecs.h \
  /usr/include/glib-2.0/gobject/gsourceclosure.h \
  /usr/include/glib-2.0/gobject/gtypemodule.h \
  /usr/include/glib-2.0/gobject/gtypeplugin.h \
  /usr/include/glib-2.0/gobject/gvaluearray.h \
  /usr/include/glib-2.0/gobject/gvaluetypes.h \
  /usr/include/glib-2.0/gio/gappinfo.h \
  /usr/include/glib-2.0/gio/gasyncresult.h \
  /usr/include/glib-2.0/gio/gbufferedinputstream.h \
  /usr/include/glib-2.0/gio/gfilterinputstream.h \
  /usr/include/glib-2.0/gio/ginputstream.h \
  /usr/include/glib-2.0/gio/gbufferedoutputstream.h \
  /usr/include/glib-2.0/gio/gfilteroutputstream.h \
  /usr/include/glib-2.0/gio/goutputstream.h \
  /usr/include/glib-2.0/gio/gcancellable.h \
  /usr/include/glib-2.0/gio/gcontenttype.h \
  /usr/include/glib-2.0/gio/gdatainputstream.h \
  /usr/include/glib-2.0/gio/gdataoutputstream.h \
  /usr/include/glib-2.0/gio/gdrive.h \
  /usr/include/glib-2.0/gio/gemblemedicon.h \
  /usr/include/glib-2.0/gio/gicon.h /usr/include/glib-2.0/gio/gemblem.h \
  /usr/include/glib-2.0/gio/gfile.h \
  /usr/include/glib-2.0/gio/gfileattribute.h \
  /usr/include/glib-2.0/gio/gfileenumerator.h \
  /usr/include/glib-2.0/gio/gfileicon.h \
  /usr/include/glib-2.0/gio/gfileinfo.h \
  /usr/include/glib-2.0/gio/gfileinputstream.h \
  /usr/include/glib-2.0/gio/gfilemonitor.h \
  /usr/include/glib-2.0/gio/gfilenamecompleter.h \
  /usr/include/glib-2.0/gio/gfileoutputstream.h \
  /usr/include/glib-2.0/gio/gioenumtypes.h \
  /usr/include/glib-2.0/gio/gioerror.h \
  /usr/include/glib-2.0/gio/giomodule.h /usr/include/glib-2.0/gmodule.h \
  /usr/include/glib-2.0/gio/gioscheduler.h \
  /usr/include/glib-2.0/gio/gloadableicon.h \
  /usr/include/glib-2.0/gio/gmemoryinputstream.h \
  /usr/include/glib-2.0/gio/gmemoryoutputstream.h \
  /usr/include/glib-2.0/gio/gmount.h \
  /usr/include/glib-2.0/gio/gmountoperation.h \
  /usr/include/glib-2.0/gio/gnativevolumemonitor.h \
  /usr/include/glib-2.0/gio/gvolumemonitor.h \
  /usr/include/glib-2.0/gio/gseekable.h \
  /usr/include/glib-2.0/gio/gsimpleasyncresult.h \
  /usr/include/glib-2.0/gio/gthemedicon.h \
  /usr/include/glib-2.0/gio/gvfs.h /usr/include/glib-2.0/gio/gvolume.h \
  /usr/include/gtk-2.0/gdk/gdkscreen.h /usr/include/cairo/cairo.h \
  /usr/include/cairo/cairo-version.h /usr/include/cairo/cairo-features.h \
  /usr/include/cairo/cairo-deprecated.h \
  /usr/include/gtk-2.0/gdk/gdktypes.h \
  /usr/include/pango-1.0/pango/pango.h \
  /usr/include/pango-1.0/pango/pango-attributes.h \
  /usr/include/pango-1.0/pango/pango-font.h \
  /usr/include/pango-1.0/pango/pango-coverage.h \
  /usr/include/pango-1.0/pango/pango-types.h \
  /usr/include/pango-1.0/pango/pango-gravity.h \
  /usr/include/pango-1.0/pango/pango-matrix.h \
  /usr/include/pango-1.0/pango/pango-script.h \
  /usr/include/pango-1.0/pango/pango-language.h \
  /usr/include/pango-1.0/pango/pango-bidi-type.h \
  /usr/include/pango-1.0/pango/pango-break.h \
  /usr/include/pango-1.0/pango/pango-item.h \
  /usr/include/pango-1.0/pango/pango-context.h \
  /usr/include/pango-1.0/pango/pango-fontmap.h \
  /usr/include/pango-1.0/pango/pango-fontset.h \
  /usr/include/pango-1.0/pango/pango-engine.h \
  /usr/include/pango-1.0/pango/pango-glyph.h \
  /usr/include/pango-1.0/pango/pango-enum-types.h \
  /usr/include/pango-1.0/pango/pango-features.h \
  /usr/include/pango-1.0/pango/pango-glyph-item.h \
  /usr/include/pango-1.0/pango/pango-layout.h \
  /usr/include/pango-1.0/pango/pango-tabs.h \
  /usr/include/pango-1.0/pango/pango-renderer.h \
  /usr/include/pango-1.0/pango/pango-utils.h \
  /usr/lib/gtk-2.0/include/gdkconfig.h \
  /usr/include/gtk-2.0/gdk/gdkdisplay.h \
  /usr/include/gtk-2.0/gdk/gdkevents.h \
  /usr/include/gtk-2.0/gdk/gdkcolor.h /usr/include/gtk-2.0/gdk/gdkdnd.h \
  /usr/include/gtk-2.0/gdk/gdkinput.h /usr/include/gtk-2.0/gdk/gdkcairo.h \
  /usr/include/gtk-2.0/gdk/gdkpixbuf.h /usr/include/gtk-2.0/gdk/gdkrgb.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-features.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-core.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-transform.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-animation.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-io.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-loader.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h \
  /usr/include/pango-1.0/pango/pangocairo.h \
  /usr/include/gtk-2.0/gdk/gdkcursor.h \
  /usr/include/gtk-2.0/gdk/gdkdisplaymanager.h \
  /usr/include/gtk-2.0/gdk/gdkdrawable.h /usr/include/gtk-2.0/gdk/gdkgc.h \
  /usr/include/gtk-2.0/gdk/gdkenumtypes.h \
  /usr/include/gtk-2.0/gdk/gdkfont.h /usr/include/gtk-2.0/gdk/gdkimage.h \
  /usr/include/gtk-2.0/gdk/gdkkeys.h /usr/include/gtk-2.0/gdk/gdkpango.h \
  /usr/include/gtk-2.0/gdk/gdkpixmap.h \
  /usr/include/gtk-2.0/gdk/gdkproperty.h \
  /usr/include/gtk-2.0/gdk/gdkregion.h \
  /usr/include/gtk-2.0/gdk/gdkselection.h \
  /usr/include/gtk-2.0/gdk/gdkspawn.h \
  /usr/include/gtk-2.0/gdk/gdktestutils.h \
  /usr/include/gtk-2.0/gdk/gdkwindow.h \
  /usr/include/gtk-2.0/gdk/gdkvisual.h \
  /home/exco/zmw/include/zmw/zmw_generated_public.h \
  /home/exco/zmw/include/zmw/zmw_widgets.h \
  /home/exco/zmw/include/zmw/http.h hello_world.c editable_text.c \
  horizontal_box.c expand.c hor_hor_box.c ver_ver_box.c ver_hor_box.c \
  vertical_box.c many_widgets.c color.c focus.c button.c menu.c \
  notebook.c tips.c drag_and_drop.c toggle.c quit.c asked.c dragger.c \
  animation.c anchor_box.c scrollbar.c scrollbar2.c viewport.c embeded.c \
  sensible.c state.c accel.c filechooser.c image.c compose.c message.c \
  test_trace.c table.c cursorin.c
main_sb.o: main_sb.c /home/exco/zmw/include/zmw/zmw.h \
  /usr/include/gtk-2.0/gdk/gdk.h \
  /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h \
  /usr/include/glib-2.0/gio/gio.h /usr/include/glib-2.0/gio/giotypes.h \
  /usr/include/glib-2.0/gio/gioenums.h \
  /usr/include/glib-2.0/glib-object.h \
  /usr/include/glib-2.0/gobject/gboxed.h \
  /usr/include/glib-2.0/gobject/gtype.h /usr/include/glib-2.0/glib.h \
  /usr/include/glib-2.0/glib/galloca.h \
  /usr/include/glib-2.0/glib/gtypes.h \
  /usr/lib/glib-2.0/include/glibconfig.h \
  /usr/include/glib-2.0/glib/gmacros.h \
  /usr/include/glib-2.0/glib/garray.h \
  /usr/include/glib-2.0/glib/gasyncqueue.h \
  /usr/include/glib-2.0/glib/gthread.h \
  /usr/include/glib-2.0/glib/gerror.h /usr/include/glib-2.0/glib/gquark.h \
  /usr/include/glib-2.0/glib/gutils.h \
  /usr/include/glib-2.0/glib/gatomic.h \
  /usr/include/glib-2.0/glib/gbacktrace.h \
  /usr/include/glib-2.0/glib/gbase64.h \
  /usr/include/glib-2.0/glib/gbookmarkfile.h \
  /usr/include/glib-2.0/glib/gcache.h /usr/include/glib-2.0/glib/glist.h \
  /usr/include/glib-2.0/glib/gmem.h /usr/include/glib-2.0/glib/gslice.h \
  /usr/include/glib-2.0/glib/gchecksum.h \
  /usr/include/glib-2.0/glib/gcompletion.h \
  /usr/include/glib-2.0/glib/gconvert.h \
  /usr/include/glib-2.0/glib/gdataset.h \
  /usr/include/glib-2.0/glib/gdate.h /usr/include/glib-2.0/glib/gdir.h \
  /usr/include/glib-2.0/glib/gfileutils.h \
  /usr/include/glib-2.0/glib/ghash.h /usr/include/glib-2.0/glib/ghook.h \
  /usr/include/glib-2.0/glib/giochannel.h \
  /usr/include/glib-2.0/glib/gmain.h /usr/include/glib-2.0/glib/gslist.h \
  /usr/include/glib-2.0/glib/gstring.h \
  /usr/include/glib-2.0/glib/gunicode.h \
  /usr/include/glib-2.0/glib/gkeyfile.h \
  /usr/include/glib-2.0/glib/gmappedfile.h \
  /usr/include/glib-2.0/glib/gmarkup.h \
  /usr/include/glib-2.0/glib/gmessages.h \
  /usr/include/glib-2.0/glib/gnode.h /usr/include/glib-2.0/glib/goption.h \
  /usr/include/glib-2.0/glib/gpattern.h \
  /usr/include/glib-2.0/glib/gprimes.h \
  /usr/include/glib-2.0/glib/gqsort.h /usr/include/glib-2.0/glib/gqueue.h \
  /usr/include/glib-2.0/glib/grand.h /usr/include/glib-2.0/glib/grel.h \
  /usr/include/glib-2.0/glib/gregex.h \
  /usr/include/glib-2.0/glib/gscanner.h \
  /usr/include/glib-2.0/glib/gsequence.h \
  /usr/include/glib-2.0/glib/gshell.h /usr/include/glib-2.0/glib/gspawn.h \
  /usr/include/glib-2.0/glib/gstrfuncs.h \
  /usr/include/glib-2.0/glib/gtestutils.h \
  /usr/include/glib-2.0/glib/gthreadpool.h \
  /usr/include/glib-2.0/glib/gtimer.h /usr/include/glib-2.0/glib/gtree.h \
  /usr/include/glib-2.0/glib/gurifuncs.h \
  /usr/include/glib-2.0/gobject/genums.h \
  /usr/include/glib-2.0/gobject/gobject.h \
  /usr/include/glib-2.0/gobject/gvalue.h \
  /usr/include/glib-2.0/gobject/gparam.h \
  /usr/include/glib-2.0/gobject/gclosure.h \
  /usr/include/glib-2.0/gobject/gsignal.h \
  /usr/include/glib-2.0/gobject/gmarshal.h \
  /usr/include/glib-2.0/gobject/gparamspecs.h \
  /usr/include/glib-2.0/gobject/gsourceclosure.h \
  /usr/include/glib-2.0/gobject/gtypemodule.h \
  /usr/include/glib-2.0/gobject/gtypeplugin.h \
  /usr/include/glib-2.0/gobject/gvaluearray.h \
  /usr/include/glib-2.0/gobject/gvaluetypes.h \
  /usr/include/glib-2.0/gio/gappinfo.h \
  /usr/include/glib-2.0/gio/gasyncresult.h \
  /usr/include/glib-2.0/gio/gbufferedinputstream.h \
  /usr/include/glib-2.0/gio/gfilterinputstream.h \
  /usr/include/glib-2.0/gio/ginputstream.h \
  /usr/include/glib-2.0/gio/gbufferedoutputstream.h \
  /usr/include/glib-2.0/gio/gfilteroutputstream.h \
  /usr/include/glib-2.0/gio/goutputstream.h \
  /usr/include/glib-2.0/gio/gcancellable.h \
  /usr/include/glib-2.0/gio/gcontenttype.h \
  /usr/include/glib-2.0/gio/gdatainputstream.h \
  /usr/include/glib-2.0/gio/gdataoutputstream.h \
  /usr/include/glib-2.0/gio/gdrive.h \
  /usr/include/glib-2.0/gio/gemblemedicon.h \
  /usr/include/glib-2.0/gio/gicon.h /usr/include/glib-2.0/gio/gemblem.h \
  /usr/include/glib-2.0/gio/gfile.h \
  /usr/include/glib-2.0/gio/gfileattribute.h \
  /usr/include/glib-2.0/gio/gfileenumerator.h \
  /usr/include/glib-2.0/gio/gfileicon.h \
  /usr/include/glib-2.0/gio/gfileinfo.h \
  /usr/include/glib-2.0/gio/gfileinputstream.h \
  /usr/include/glib-2.0/gio/gfilemonitor.h \
  /usr/include/glib-2.0/gio/gfilenamecompleter.h \
  /usr/include/glib-2.0/gio/gfileoutputstream.h \
  /usr/include/glib-2.0/gio/gioenumtypes.h \
  /usr/include/glib-2.0/gio/gioerror.h \
  /usr/include/glib-2.0/gio/giomodule.h /usr/include/glib-2.0/gmodule.h \
  /usr/include/glib-2.0/gio/gioscheduler.h \
  /usr/include/glib-2.0/gio/gloadableicon.h \
  /usr/include/glib-2.0/gio/gmemoryinputstream.h \
  /usr/include/glib-2.0/gio/gmemoryoutputstream.h \
  /usr/include/glib-2.0/gio/gmount.h \
  /usr/include/glib-2.0/gio/gmountoperation.h \
  /usr/include/glib-2.0/gio/gnativevolumemonitor.h \
  /usr/include/glib-2.0/gio/gvolumemonitor.h \
  /usr/include/glib-2.0/gio/gseekable.h \
  /usr/include/glib-2.0/gio/gsimpleasyncresult.h \
  /usr/include/glib-2.0/gio/gthemedicon.h \
  /usr/include/glib-2.0/gio/gvfs.h /usr/include/glib-2.0/gio/gvolume.h \
  /usr/include/gtk-2.0/gdk/gdkscreen.h /usr/include/cairo/cairo.h \
  /usr/include/cairo/cairo-version.h /usr/include/cairo/cairo-features.h \
  /usr/include/cairo/cairo-deprecated.h \
  /usr/include/gtk-2.0/gdk/gdktypes.h \
  /usr/include/pango-1.0/pango/pango.h \
  /usr/include/pango-1.0/pango/pango-attributes.h \
  /usr/include/pango-1.0/pango/pango-font.h \
  /usr/include/pango-1.0/pango/pango-coverage.h \
  /usr/include/pango-1.0/pango/pango-types.h \
  /usr/include/pango-1.0/pango/pango-gravity.h \
  /usr/include/pango-1.0/pango/pango-matrix.h \
  /usr/include/pango-1.0/pango/pango-script.h \
  /usr/include/pango-1.0/pango/pango-language.h \
  /usr/include/pango-1.0/pango/pango-bidi-type.h \
  /usr/include/pango-1.0/pango/pango-break.h \
  /usr/include/pango-1.0/pango/pango-item.h \
  /usr/include/pango-1.0/pango/pango-context.h \
  /usr/include/pango-1.0/pango/pango-fontmap.h \
  /usr/include/pango-1.0/pango/pango-fontset.h \
  /usr/include/pango-1.0/pango/pango-engine.h \
  /usr/include/pango-1.0/pango/pango-glyph.h \
  /usr/include/pango-1.0/pango/pango-enum-types.h \
  /usr/include/pango-1.0/pango/pango-features.h \
  /usr/include/pango-1.0/pango/pango-glyph-item.h \
  /usr/include/pango-1.0/pango/pango-layout.h \
  /usr/include/pango-1.0/pango/pango-tabs.h \
  /usr/include/pango-1.0/pango/pango-renderer.h \
  /usr/include/pango-1.0/pango/pango-utils.h \
  /usr/lib/gtk-2.0/include/gdkconfig.h \
  /usr/include/gtk-2.0/gdk/gdkdisplay.h \
  /usr/include/gtk-2.0/gdk/gdkevents.h \
  /usr/include/gtk-2.0/gdk/gdkcolor.h /usr/include/gtk-2.0/gdk/gdkdnd.h \
  /usr/include/gtk-2.0/gdk/gdkinput.h /usr/include/gtk-2.0/gdk/gdkcairo.h \
  /usr/include/gtk-2.0/gdk/gdkpixbuf.h /usr/include/gtk-2.0/gdk/gdkrgb.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-features.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-core.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-transform.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-animation.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-io.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-loader.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h \
  /usr/include/pango-1.0/pango/pangocairo.h \
  /usr/include/gtk-2.0/gdk/gdkcursor.h \
  /usr/include/gtk-2.0/gdk/gdkdisplaymanager.h \
  /usr/include/gtk-2.0/gdk/gdkdrawable.h /usr/include/gtk-2.0/gdk/gdkgc.h \
  /usr/include/gtk-2.0/gdk/gdkenumtypes.h \
  /usr/include/gtk-2.0/gdk/gdkfont.h /usr/include/gtk-2.0/gdk/gdkimage.h \
  /usr/include/gtk-2.0/gdk/gdkkeys.h /usr/include/gtk-2.0/gdk/gdkpango.h \
  /usr/include/gtk-2.0/gdk/gdkpixmap.h \
  /usr/include/gtk-2.0/gdk/gdkproperty.h \
  /usr/include/gtk-2.0/gdk/gdkregion.h \
  /usr/include/gtk-2.0/gdk/gdkselection.h \
  /usr/include/gtk-2.0/gdk/gdkspawn.h \
  /usr/include/gtk-2.0/gdk/gdktestutils.h \
  /usr/include/gtk-2.0/gdk/gdkwindow.h \
  /usr/include/gtk-2.0/gdk/gdkvisual.h \
  /home/exco/zmw/include/zmw/zmw_generated_public.h \
  /home/exco/zmw/include/zmw/zmw_widgets.h \
  /home/exco/zmw/include/zmw/http.h
main_trace.o: main_trace.c /home/exco/zmw/include/zmw/zmw.h \
  /usr/include/gtk-2.0/gdk/gdk.h \
  /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h \
  /usr/include/glib-2.0/gio/gio.h /usr/include/glib-2.0/gio/giotypes.h \
  /usr/include/glib-2.0/gio/gioenums.h \
  /usr/include/glib-2.0/glib-object.h \
  /usr/include/glib-2.0/gobject/gboxed.h \
  /usr/include/glib-2.0/gobject/gtype.h /usr/include/glib-2.0/glib.h \
  /usr/include/glib-2.0/glib/galloca.h \
  /usr/include/glib-2.0/glib/gtypes.h \
  /usr/lib/glib-2.0/include/glibconfig.h \
  /usr/include/glib-2.0/glib/gmacros.h \
  /usr/include/glib-2.0/glib/garray.h \
  /usr/include/glib-2.0/glib/gasyncqueue.h \
  /usr/include/glib-2.0/glib/gthread.h \
  /usr/include/glib-2.0/glib/gerror.h /usr/include/glib-2.0/glib/gquark.h \
  /usr/include/glib-2.0/glib/gutils.h \
  /usr/include/glib-2.0/glib/gatomic.h \
  /usr/include/glib-2.0/glib/gbacktrace.h \
  /usr/include/glib-2.0/glib/gbase64.h \
  /usr/include/glib-2.0/glib/gbookmarkfile.h \
  /usr/include/glib-2.0/glib/gcache.h /usr/include/glib-2.0/glib/glist.h \
  /usr/include/glib-2.0/glib/gmem.h /usr/include/glib-2.0/glib/gslice.h \
  /usr/include/glib-2.0/glib/gchecksum.h \
  /usr/include/glib-2.0/glib/gcompletion.h \
  /usr/include/glib-2.0/glib/gconvert.h \
  /usr/include/glib-2.0/glib/gdataset.h \
  /usr/include/glib-2.0/glib/gdate.h /usr/include/glib-2.0/glib/gdir.h \
  /usr/include/glib-2.0/glib/gfileutils.h \
  /usr/include/glib-2.0/glib/ghash.h /usr/include/glib-2.0/glib/ghook.h \
  /usr/include/glib-2.0/glib/giochannel.h \
  /usr/include/glib-2.0/glib/gmain.h /usr/include/glib-2.0/glib/gslist.h \
  /usr/include/glib-2.0/glib/gstring.h \
  /usr/include/glib-2.0/glib/gunicode.h \
  /usr/include/glib-2.0/glib/gkeyfile.h \
  /usr/include/glib-2.0/glib/gmappedfile.h \
  /usr/include/glib-2.0/glib/gmarkup.h \
  /usr/include/glib-2.0/glib/gmessages.h \
  /usr/include/glib-2.0/glib/gnode.h /usr/include/glib-2.0/glib/goption.h \
  /usr/include/glib-2.0/glib/gpattern.h \
  /usr/include/glib-2.0/glib/gprimes.h \
  /usr/include/glib-2.0/glib/gqsort.h /usr/include/glib-2.0/glib/gqueue.h \
  /usr/include/glib-2.0/glib/grand.h /usr/include/glib-2.0/glib/grel.h \
  /usr/include/glib-2.0/glib/gregex.h \
  /usr/include/glib-2.0/glib/gscanner.h \
  /usr/include/glib-2.0/glib/gsequence.h \
  /usr/include/glib-2.0/glib/gshell.h /usr/include/glib-2.0/glib/gspawn.h \
  /usr/include/glib-2.0/glib/gstrfuncs.h \
  /usr/include/glib-2.0/glib/gtestutils.h \
  /usr/include/glib-2.0/glib/gthreadpool.h \
  /usr/include/glib-2.0/glib/gtimer.h /usr/include/glib-2.0/glib/gtree.h \
  /usr/include/glib-2.0/glib/gurifuncs.h \
  /usr/include/glib-2.0/gobject/genums.h \
  /usr/include/glib-2.0/gobject/gobject.h \
  /usr/include/glib-2.0/gobject/gvalue.h \
  /usr/include/glib-2.0/gobject/gparam.h \
  /usr/include/glib-2.0/gobject/gclosure.h \
  /usr/include/glib-2.0/gobject/gsignal.h \
  /usr/include/glib-2.0/gobject/gmarshal.h \
  /usr/include/glib-2.0/gobject/gparamspecs.h \
  /usr/include/glib-2.0/gobject/gsourceclosure.h \
  /usr/include/glib-2.0/gobject/gtypemodule.h \
  /usr/include/glib-2.0/gobject/gtypeplugin.h \
  /usr/include/glib-2.0/gobject/gvaluearray.h \
  /usr/include/glib-2.0/gobject/gvaluetypes.h \
  /usr/include/glib-2.0/gio/gappinfo.h \
  /usr/include/glib-2.0/gio/gasyncresult.h \
  /usr/include/glib-2.0/gio/gbufferedinputstream.h \
  /usr/include/glib-2.0/gio/gfilterinputstream.h \
  /usr/include/glib-2.0/gio/ginputstream.h \
  /usr/include/glib-2.0/gio/gbufferedoutputstream.h \
  /usr/include/glib-2.0/gio/gfilteroutputstream.h \
  /usr/include/glib-2.0/gio/goutputstream.h \
  /usr/include/glib-2.0/gio/gcancellable.h \
  /usr/include/glib-2.0/gio/gcontenttype.h \
  /usr/include/glib-2.0/gio/gdatainputstream.h \
  /usr/include/glib-2.0/gio/gdataoutputstream.h \
  /usr/include/glib-2.0/gio/gdrive.h \
  /usr/include/glib-2.0/gio/gemblemedicon.h \
  /usr/include/glib-2.0/gio/gicon.h /usr/include/glib-2.0/gio/gemblem.h \
  /usr/include/glib-2.0/gio/gfile.h \
  /usr/include/glib-2.0/gio/gfileattribute.h \
  /usr/include/glib-2.0/gio/gfileenumerator.h \
  /usr/include/glib-2.0/gio/gfileicon.h \
  /usr/include/glib-2.0/gio/gfileinfo.h \
  /usr/include/glib-2.0/gio/gfileinputstream.h \
  /usr/include/glib-2.0/gio/gfilemonitor.h \
  /usr/include/glib-2.0/gio/gfilenamecompleter.h \
  /usr/include/glib-2.0/gio/gfileoutputstream.h \
  /usr/include/glib-2.0/gio/gioenumtypes.h \
  /usr/include/glib-2.0/gio/gioerror.h \
  /usr/include/glib-2.0/gio/giomodule.h /usr/include/glib-2.0/gmodule.h \
  /usr/include/glib-2.0/gio/gioscheduler.h \
  /usr/include/glib-2.0/gio/gloadableicon.h \
  /usr/include/glib-2.0/gio/gmemoryinputstream.h \
  /usr/include/glib-2.0/gio/gmemoryoutputstream.h \
  /usr/include/glib-2.0/gio/gmount.h \
  /usr/include/glib-2.0/gio/gmountoperation.h \
  /usr/include/glib-2.0/gio/gnativevolumemonitor.h \
  /usr/include/glib-2.0/gio/gvolumemonitor.h \
  /usr/include/glib-2.0/gio/gseekable.h \
  /usr/include/glib-2.0/gio/gsimpleasyncresult.h \
  /usr/include/glib-2.0/gio/gthemedicon.h \
  /usr/include/glib-2.0/gio/gvfs.h /usr/include/glib-2.0/gio/gvolume.h \
  /usr/include/gtk-2.0/gdk/gdkscreen.h /usr/include/cairo/cairo.h \
  /usr/include/cairo/cairo-version.h /usr/include/cairo/cairo-features.h \
  /usr/include/cairo/cairo-deprecated.h \
  /usr/include/gtk-2.0/gdk/gdktypes.h \
  /usr/include/pango-1.0/pango/pango.h \
  /usr/include/pango-1.0/pango/pango-attributes.h \
  /usr/include/pango-1.0/pango/pango-font.h \
  /usr/include/pango-1.0/pango/pango-coverage.h \
  /usr/include/pango-1.0/pango/pango-types.h \
  /usr/include/pango-1.0/pango/pango-gravity.h \
  /usr/include/pango-1.0/pango/pango-matrix.h \
  /usr/include/pango-1.0/pango/pango-script.h \
  /usr/include/pango-1.0/pango/pango-language.h \
  /usr/include/pango-1.0/pango/pango-bidi-type.h \
  /usr/include/pango-1.0/pango/pango-break.h \
  /usr/include/pango-1.0/pango/pango-item.h \
  /usr/include/pango-1.0/pango/pango-context.h \
  /usr/include/pango-1.0/pango/pango-fontmap.h \
  /usr/include/pango-1.0/pango/pango-fontset.h \
  /usr/include/pango-1.0/pango/pango-engine.h \
  /usr/include/pango-1.0/pango/pango-glyph.h \
  /usr/include/pango-1.0/pango/pango-enum-types.h \
  /usr/include/pango-1.0/pango/pango-features.h \
  /usr/include/pango-1.0/pango/pango-glyph-item.h \
  /usr/include/pango-1.0/pango/pango-layout.h \
  /usr/include/pango-1.0/pango/pango-tabs.h \
  /usr/include/pango-1.0/pango/pango-renderer.h \
  /usr/include/pango-1.0/pango/pango-utils.h \
  /usr/lib/gtk-2.0/include/gdkconfig.h \
  /usr/include/gtk-2.0/gdk/gdkdisplay.h \
  /usr/include/gtk-2.0/gdk/gdkevents.h \
  /usr/include/gtk-2.0/gdk/gdkcolor.h /usr/include/gtk-2.0/gdk/gdkdnd.h \
  /usr/include/gtk-2.0/gdk/gdkinput.h /usr/include/gtk-2.0/gdk/gdkcairo.h \
  /usr/include/gtk-2.0/gdk/gdkpixbuf.h /usr/include/gtk-2.0/gdk/gdkrgb.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-features.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-core.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-transform.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-animation.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-io.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-loader.h \
  /usr/include/gtk-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h \
  /usr/include/pango-1.0/pango/pangocairo.h \
  /usr/include/gtk-2.0/gdk/gdkcursor.h \
  /usr/include/gtk-2.0/gdk/gdkdisplaymanager.h \
  /usr/include/gtk-2.0/gdk/gdkdrawable.h /usr/include/gtk-2.0/gdk/gdkgc.h \
  /usr/include/gtk-2.0/gdk/gdkenumtypes.h \
  /usr/include/gtk-2.0/gdk/gdkfont.h /usr/include/gtk-2.0/gdk/gdkimage.h \
  /usr/include/gtk-2.0/gdk/gdkkeys.h /usr/include/gtk-2.0/gdk/gdkpango.h \
  /usr/include/gtk-2.0/gdk/gdkpixmap.h \
  /usr/include/gtk-2.0/gdk/gdkproperty.h \
  /usr/include/gtk-2.0/gdk/gdkregion.h \
  /usr/include/gtk-2.0/gdk/gdkselection.h \
  /usr/include/gtk-2.0/gdk/gdkspawn.h \
  /usr/include/gtk-2.0/gdk/gdktestutils.h \
  /usr/include/gtk-2.0/gdk/gdkwindow.h \
  /usr/include/gtk-2.0/gdk/gdkvisual.h \
  /home/exco/zmw/include/zmw/zmw_generated_public.h \
  /home/exco/zmw/include/zmw/zmw_widgets.h \
  /home/exco/zmw/include/zmw/http.h test_trace.c many_widgets.c \
  notebook.c
many_widgets.o: many_widgets.c
menu.o: menu.c
message.o: message.c
notebook.o: notebook.c
quit.o: quit.c
scrollbar.o: scrollbar.c
scrollbar2.o: scrollbar2.c
sensible.o: sensible.c
state.o: state.c
table.o: table.c
test_trace.o: test_trace.c
tips.o: tips.c
toggle.o: toggle.c
ver_hor_box.o: ver_hor_box.c
ver_ver_box.o: ver_ver_box.c
vertical_box.o: vertical_box.c
viewport.o: viewport.c
